export const emptyLegsStats = [
  { label: "AVAILABLE LEGS", value: "3", tone: "success" },
  { label: "MATCHED", value: "1", tone: "info" },
  { label: "BOOKED", value: "0", tone: "warning" },
  { label: "TOTAL VALUE", value: "$52,500", tone: "foreground" },
];

export const emptyLegsStatusFilterOptions = ["All Status", "Available", "Matched", "Booked", "Expired"];

export const emptyLegsData = [
  {
    id: "EL-1001",
    origin: "Miami",
    destination: "Teterboro",
    date: "Aug 12, 2026",
    departureTime: "10:00 AM",
    aircraft: "Challenger 605",
    operator: "VistaJet",
    price: "$12,500",
    priceRaw: 12500,
    expiry: "Aug 12",
    expiryTime: "18:00",
    matches: 3,
    status: "Available", // "Available", "Matched", "Booked", "Expired"
    notes: "Internal notes visible to brokers only...",
  },
  {
    id: "EL-1002",
    origin: "Fort Lauderdale",
    destination: "Teterboro",
    date: "Aug 14, 2026",
    departureTime: "14:00 PM",
    aircraft: "Citation XLS",
    operator: "NetJets",
    price: "$8,500",
    priceRaw: 8500,
    expiry: "Aug 14",
    expiryTime: "20:00",
    matches: 1,
    status: "Available",
    notes: "Direct empty leg repositioning flight.",
  },
  {
    id: "EL-1003",
    origin: "Los Angeles",
    destination: "Miami",
    date: "Aug 16, 2026",
    departureTime: "11:30 AM",
    aircraft: "Gulfstream G450",
    operator: "ExecuJet",
    price: "$24,500",
    priceRaw: 24500,
    expiry: "Aug 16",
    expiryTime: "17:00",
    matches: 2,
    status: "Available",
    notes: "Coast-to-coast heavy jet empty leg.",
  },
  {
    id: "EL-1004",
    origin: "Chicago",
    destination: "New York",
    date: "Aug 10, 2026",
    departureTime: "09:00 AM",
    aircraft: "Citation Latitude",
    operator: "Global Wings",
    price: "$7,500",
    priceRaw: 7500,
    expiry: "Aug 10",
    expiryTime: "15:00",
    matches: 1,
    status: "Matched",
    notes: "Matched with client Robert Walsh.",
  },
];
