export const operatorSourcingStats = [
  { label: "OPEN REQUEST", value: "4", tone: "foreground" },
  { label: "AWAITING RESPONSE", value: "3", tone: "info" },
  { label: "QUOTE RECEIVED", value: "15", tone: "purple" },
  { label: "Avg Response TIME", value: "2.4hrs", tone: "foreground" },
  { label: "SOURCED THIS MONTH", value: "18", tone: "success" },
];

export const sourcingStatusOptions = ["All", "Requested", "Sourcing", "Pending Operator Quote", "Source Complete"];
export const sourcingBrokerOptions = ["All", "Benny", "Mark", "Barry", "Ari"];
export const sourcingPaymentOptions = ["All", "Paid", "Pending", "Partially Paid"];

export const sourcingAircraftCategoryOptions = [
  "Turboprop",
  "Light Jet",
  "Midsize Jet",
  "Super Midsize",
  "Heavy Jet",
  "Ultra Long Range",
];

export const sourcingOperatorOptions = [
  "ExecuJet",
  "VistaJet",
  "Flexjet",
  "Global Wings",
  "NetJets",
  "Wheels Up",
  "Air Charter Group",
  "Jet Aviation",
];

const AMENITIES = "WIFI + full catering included";

export const sourcingRequests = [
  {
    id: "#TJ-1048",
    client: "Jonathan Reed",
    broker: "Benny",
    from: "KTEB",
    to: "KPBI",
    departure: "Aug 24, 2026",
    departureTime: "10:00 AM",
    arrivalTime: "1:05 PM",
    duration: "3h 05m",
    aircraftNeeded: "Heavy Jet",
    operatorsContacted: 4,
    responses: 4,
    budget: "$55,000",
    deadline: "Aug 15, 2026",
    status: "Requested",
    depositStatus: "Pending",
    notes: "Client needs WiFi and catering on board. Prefers Global series.",
    quotes: [
      { id: "q1", operator: "ExecuJet", aircraft: "Gulfstream G550", tailNumber: "N780EX", price: "$58,500", amenities: AMENITIES, responseTime: "2h", status: "Pending" },
      { id: "q2", operator: "VistaJet", aircraft: "Challenger 350", tailNumber: "N100FJ", price: "$67,000", amenities: AMENITIES, responseTime: "4h", status: "Approved" },
      { id: "q3", operator: "Flexjet", aircraft: "Challenger 350", tailNumber: "N100FJ", price: "$67,000", amenities: AMENITIES, responseTime: "2h", status: "Rejected" },
      { id: "q4", operator: "Global Wings", aircraft: "Citation Latitude", tailNumber: "N333GW", price: "$54,200", amenities: AMENITIES, responseTime: "3h", status: "Vendor Pending" },
    ],
  },
  {
    id: "TJ-2402",
    client: "Hope Sterling",
    broker: "Benny",
    from: "KTEB",
    to: "KMIA",
    departure: "Aug 24, 2026",
    departureTime: "9:15 AM",
    arrivalTime: "12:40 PM",
    duration: "3h 25m",
    aircraftNeeded: "Ultra Long Range",
    operatorsContacted: 4,
    responses: 3,
    budget: "$95,000",
    deadline: "Aug 20, 2026",
    status: "Sourcing",
    depositStatus: "Paid",
    notes: "Repeat client — always books the same cabin configuration.",
    quotes: [
      { id: "q1", operator: "VistaJet", aircraft: "Global 7500", tailNumber: "N750VJ", price: "$92,000", amenities: AMENITIES, responseTime: "3h", status: "Pending" },
      { id: "q2", operator: "NetJets", aircraft: "Global 6000", tailNumber: "N600NJ", price: "$97,500", amenities: AMENITIES, responseTime: "5h", status: "Approved" },
      { id: "q3", operator: "Jet Aviation", aircraft: "Global 6000", tailNumber: "N601JA", price: "$99,000", amenities: AMENITIES, responseTime: "6h", status: "Vendor Pending" },
    ],
  },
  {
    id: "TJ-2403",
    client: "Emily Carter",
    broker: "Mark",
    from: "KMIA",
    to: "EGLL",
    departure: "Aug 18, 2026",
    departureTime: "7:30 PM",
    arrivalTime: "9:10 AM",
    duration: "8h 40m",
    aircraftNeeded: "Light Jet",
    operatorsContacted: 3,
    responses: 2,
    budget: "$18,000",
    deadline: "Aug 21, 2026",
    status: "Sourcing",
    depositStatus: "Partially Paid",
    notes: "Client is price sensitive — flag any quote over budget before sending.",
    quotes: [
      { id: "q1", operator: "Air Charter Group", aircraft: "Citation XLS", tailNumber: "N235AC", price: "$17,200", amenities: AMENITIES, responseTime: "2h", status: "Pending" },
      { id: "q2", operator: "Wheels Up", aircraft: "Citation Excel", tailNumber: "N236WU", price: "$18,900", amenities: AMENITIES, responseTime: "3h", status: "Rejected" },
    ],
  },
  {
    id: "TJ-2404",
    client: "Robert Walsh",
    broker: "Barry",
    from: "KTEB",
    to: "KPBI",
    departure: "Aug 22, 2026",
    departureTime: "8:00 AM",
    arrivalTime: "10:35 AM",
    duration: "2h 35m",
    aircraftNeeded: "Midsize Jet",
    operatorsContacted: 5,
    responses: 4,
    budget: "$28,000",
    deadline: "Aug 10, 2026",
    status: "Pending Operator Quote",
    depositStatus: "Paid",
    notes: "Confirm pet-friendly cabin before booking — traveling with a service dog.",
    quotes: [
      { id: "q1", operator: "Flexjet", aircraft: "Praetor 500", tailNumber: "N500FX", price: "$26,800", amenities: AMENITIES, responseTime: "1h", status: "Approved" },
      { id: "q2", operator: "ExecuJet", aircraft: "Citation Latitude", tailNumber: "N334EJ", price: "$27,500", amenities: AMENITIES, responseTime: "2h", status: "Pending" },
      { id: "q3", operator: "Wheels Up", aircraft: "Citation XLS", tailNumber: "N237WU", price: "$29,100", amenities: AMENITIES, responseTime: "4h", status: "Rejected" },
      { id: "q4", operator: "Jet Aviation", aircraft: "Praetor 500", tailNumber: "N501JA", price: "$28,750", amenities: AMENITIES, responseTime: "3h", status: "Vendor Pending" },
    ],
  },
  {
    id: "TJ-2405",
    client: "Hope Sterling",
    broker: "Benny",
    from: "KTEB",
    to: "KPBI",
    departure: "Aug 15, 2026",
    departureTime: "10:00 AM",
    arrivalTime: "12:45 PM",
    duration: "2h 45m",
    aircraftNeeded: "Midsize Jet",
    operatorsContacted: 4,
    responses: 4,
    budget: "$79,000",
    deadline: "Aug 10, 2026",
    status: "Source Complete",
    depositStatus: "Paid",
    notes: "Sourcing complete — awaiting final operator confirmation.",
    quotes: [
      { id: "q1", operator: "VistaJet", aircraft: "Challenger 350", tailNumber: "N351VJ", price: "$76,200", amenities: AMENITIES, responseTime: "2h", status: "Approved" },
      { id: "q2", operator: "NetJets", aircraft: "Challenger 350", tailNumber: "N352NJ", price: "$78,900", amenities: AMENITIES, responseTime: "3h", status: "Rejected" },
      { id: "q3", operator: "Flexjet", aircraft: "Challenger 350", tailNumber: "N353FX", price: "$79,400", amenities: AMENITIES, responseTime: "4h", status: "Rejected" },
      { id: "q4", operator: "ExecuJet", aircraft: "Challenger 350", tailNumber: "N354EJ", price: "$77,600", amenities: AMENITIES, responseTime: "2h", status: "Vendor Pending" },
    ],
  },
  {
    id: "TJ-2409",
    client: "Marcus Webb",
    broker: "Barry",
    from: "KHOU",
    to: "MMUN",
    departure: "Aug 28, 2026",
    departureTime: "6:45 AM",
    arrivalTime: "9:20 AM",
    duration: "2h 35m",
    aircraftNeeded: "Super Midsize",
    operatorsContacted: 3,
    responses: 1,
    budget: "$41,000",
    deadline: "Aug 24, 2026",
    status: "Requested",
    depositStatus: "Pending",
    notes: "International trip — confirm customs/handling at MMUN in advance.",
    quotes: [
      { id: "q1", operator: "Global Wings", aircraft: "Challenger 605", tailNumber: "N605GW", price: "$39,800", amenities: AMENITIES, responseTime: "5h", status: "Pending" },
    ],
  },
  {
    id: "TJ-2410",
    client: "Tyler Grant",
    broker: "Ari",
    from: "KMDW",
    to: "KFLL",
    departure: "Sep 12, 2026",
    departureTime: "11:15 AM",
    arrivalTime: "2:30 PM",
    duration: "3h 15m",
    aircraftNeeded: "Light Jet",
    operatorsContacted: 2,
    responses: 0,
    budget: "$22,500",
    deadline: "Sep 5, 2026",
    status: "Requested",
    depositStatus: "Pending",
    notes: "Awaiting first operator responses.",
    quotes: [],
  },
  {
    id: "TJ-2413",
    client: "Chris Dalton",
    broker: "Ari",
    from: "KDAL",
    to: "KASE",
    departure: "Sep 18, 2026",
    departureTime: "9:00 AM",
    arrivalTime: "10:50 AM",
    duration: "1h 50m",
    aircraftNeeded: "Turboprop",
    operatorsContacted: 3,
    responses: 3,
    budget: "$14,200",
    deadline: "Sep 10, 2026",
    status: "Sourcing",
    depositStatus: "Partially Paid",
    notes: "High-altitude airport — confirm aircraft is rated for Aspen approach.",
    quotes: [
      { id: "q1", operator: "Air Charter Group", aircraft: "King Air 350", tailNumber: "N351AC", price: "$13,600", amenities: AMENITIES, responseTime: "1h", status: "Approved" },
      { id: "q2", operator: "Wheels Up", aircraft: "King Air 350", tailNumber: "N352WU", price: "$14,050", amenities: AMENITIES, responseTime: "2h", status: "Pending" },
      { id: "q3", operator: "Jet Aviation", aircraft: "King Air 350", tailNumber: "N353JA", price: "$14,800", amenities: AMENITIES, responseTime: "3h", status: "Rejected" },
    ],
  },
];
