export const operatorPaymentsStats = [
  { label: "TOTAL OUTSTANDING", value: "$72,200", tone: "destructive" },
  { label: "TOTAL PAID", value: "$74,200", tone: "success" },
  { label: "DUE THIS WEEK", value: "1", tone: "warning" },
  { label: "TOTAL PAYABLE", value: "$146,400", tone: "foreground" },
];

export const operatorPaymentsStatusFilterOptions = [
  "All Status",
  "Paid",
  "Partially Paid",
  "Overdue",
  "Due",
  "Pending",
  "Cancelled",
];

export const operatorPaymentsData = [
  {
    id: "OP-2026-045",
    operator: "FlexJet",
    tripId: "TJ-1051",
    amount: "$51,000",
    amountRaw: 51000,
    paid: "$0",
    paidRaw: 0,
    balance: "$51,100",
    balanceRaw: 51100,
    due: "Aug 20, 2026",
    status: "Pending",
    broker: "Mark",
    method: "Wire Transfer",
    notes: "",
  },
  {
    id: "OP-2026-046",
    operator: "VistaJet",
    tripId: "TJ-1052",
    amount: "$62,000",
    amountRaw: 62000,
    paid: "$62,000",
    paidRaw: 62000,
    balance: "$0",
    balanceRaw: 0,
    due: "-",
    status: "Paid",
    broker: "Barry",
    method: "Credit Card",
    notes: "",
  },
  {
    id: "OP-2026-047",
    operator: "VistaJet",
    tripId: "TJ-1043",
    amount: "$14,800",
    amountRaw: 14800,
    paid: "$0",
    paidRaw: 0,
    balance: "$14,800",
    balanceRaw: 14800,
    due: "Aug 10, 2026",
    status: "Due",
    broker: "Mark",
    method: "Wire Transfer",
    notes: "",
  },
  {
    id: "OP-2026-048",
    operator: "NetJets",
    tripId: "TJ-1046",
    amount: "$6,400",
    amountRaw: 6400,
    paid: "$0",
    paidRaw: 0,
    balance: "$6,400",
    balanceRaw: 6400,
    due: "Aug 16, 2026",
    status: "Pending",
    broker: "Barry",
    method: "Check",
    notes: "",
  },
  {
    id: "OP-2026-049",
    operator: "ExecuJet",
    tripId: "TJ-1026",
    amount: "$12,200",
    amountRaw: 12200,
    paid: "$12,200",
    paidRaw: 12200,
    balance: "$0",
    balanceRaw: 0,
    due: "Aug 5, 2026",
    status: "Paid",
    broker: "Barry",
    method: "ACH",
    notes: "",
  },
];
