export const taskColumns = [
  { key: "To Do", label: "To Do", accentColor: "#d9d9d9" },
  { key: "In Progress", label: "In Progress", accentColor: "#155dfc" },
  { key: "Waiting on Client", label: "Waiting on Client", accentColor: "#155dfc" },
  { key: "Waiting on Operator", label: "Waiting on Operator", accentColor: "#b44ff3" },
  { key: "Completed", label: "Completed", accentColor: "#00b274" },
];

export const taskFilterOptions = ["My Tasks", "Everyone", "Due Today", "Overdue", "High priority"];

export const taskPriorityOptions = ["Low", "Medium", "High", "Urgent"];

export const taskAssigneeOptions = ["Barry", "Benny", "Mark", "Ari"];

export const tasksData = [
  {
    id: "TSK-001",
    title: "Send quote to Hope Sterling - Miami round trip",
    description: "Prepare and send the quote for the Miami round trip request.",
    status: "To Do",
    priority: "High",
    dueDate: "Aug 12",
    client: "Hope Sterling",
    trip: "TJ-1048",
    assignee: "Barry",
    auto: false,
    checklist: [],
    notes: "",
  },
  {
    id: "TSK-002",
    title: "Confirm operator availability for TJ-2405",
    description: "Reach out to shortlisted operators to confirm aircraft availability.",
    status: "To Do",
    priority: "High",
    dueDate: "Aug 13",
    client: "Sophia Morgan",
    trip: "TJ-1045",
    assignee: "Ari",
    auto: true,
    checklist: [],
    notes: "",
  },
  {
    id: "TSK-003",
    title: "Collect Payment form Robert Walsh",
    description: "Follow up with Robert Walsh to collect the outstanding payment.",
    status: "In Progress",
    priority: "Urgent",
    dueDate: "Aug 10",
    client: "Robert Walsh",
    trip: "TJ-1047",
    assignee: "Barry",
    auto: true,
    checklist: [],
    notes: "",
  },
  {
    id: "TSK-004",
    title: "Upload Itinerary fro TJ-1046 - Sarah Chen",
    description: "Upload the finalized itinerary document to the trip record.",
    status: "In Progress",
    priority: "Medium",
    dueDate: "Aug 14",
    client: "Sarah Chen",
    trip: "TJ-1045",
    assignee: "Mark",
    auto: true,
    checklist: [],
    notes: "",
  },
  {
    id: "TSK-005",
    title: "Waiting for catering confirmation from cleint",
    description: "Awaiting client confirmation on the catering selection.",
    status: "Waiting on Client",
    priority: "Medium",
    dueDate: "Aug 11",
    client: "Emily Carter",
    trip: "TJ-1047",
    assignee: "Barry",
    auto: true,
    checklist: [],
    notes: "",
  },
  {
    id: "TSK-006",
    title: "VistaJet operator payment — due tomorrow",
    description: "VistaJet operator payment — due tomorrow",
    status: "Waiting on Operator",
    priority: "High",
    dueDate: "Aug 15",
    client: "VistaJet",
    trip: "TJ-1047",
    assignee: "Mark",
    auto: true,
    checklist: [{ id: "CHK-1", text: "Hey Task", done: false }],
    notes: "VistaJet operator payment — due tomorrow",
  },
  {
    id: "TSK-007",
    title: "Waiting for catering confirmation from cleint",
    description: "Awaiting client confirmation on the catering selection.",
    status: "Completed",
    priority: "Low",
    dueDate: "Aug 6",
    client: "Emily Carter",
    trip: "TJ-1047",
    assignee: "Barry",
    auto: true,
    checklist: [],
    notes: "",
  },
];
