export const aircraftCategoryOptions = [
  "All Categories",
  "Heavy Jet",
  "Light Jet",
  "Midsize Jet",
  "Super Midsize",
  "Ultra Long Range",
  "Turboprop",
  "VIP Airliner",
];

export const aircraftTypeSelectOptions = [
  "Heavy Jet",
  "Light Jet",
  "Midsize Jet",
  "Super Midsize",
  "Ultra Long Range",
  "Turboprop",
  "VIP Airliner",
];

export const aircraftStatusOptions = ["All Status", "Available", "In Service", "Maintenance", "Inactive"];

export const aircraftStatusSelectOptions = ["Available", "In Service", "Maintenance", "Inactive"];

export const aircraftOperatorSelectOptions = [
  "Unassigned",
  "ExecuJet",
  "FlexJet",
  "VistaJet",
  "NetJets",
  "Jet Aviation",
  "Air Charter Group",
  "Rocky Mountain Air",
];

export const aircraftStats = [
  { label: "TOTAL AIRCRAFT", value: 6 },
  { label: "AVAILABLE", value: 4, tone: "success" },
  { label: "IN SERVICE", value: 1, tone: "purple" },
  { label: "MAINTENANCE", value: 1, tone: "destructive" },
];

export const aircraftData = [
  {
    id: "AC-1001",
    model: "Gulfstream G550",
    tail: "N780EX",
    category: "Heavy Jet",
    operator: "ExecuJet",
    operatorId: "OP-1003",
    capacity: "14 pax",
    paxCount: 14,
    rangeNm: "6,750",
    rangeNum: 6750,
    year: 2019,
    status: "Available",
    trips: 12,
    homeBase: "Zurich (LSZH)",
    registration: "N780EX",
    manufacturer: "Gulfstream Aerospace",
    modelYear: "2019",
    maxPassengers: "14",
    maxRange: "6,750 nm",
    maxSpeed: "Mach 0.885",
    cruiseSpeed: "Mach 0.80",
    serviceCeiling: "51,000 ft",
    baggageCapacity: "226 cu ft",
    cabinLength: "50.1 ft",
    maxTakeoffWeight: "96,000 lb",
    emptyWeight: "48,300 lb",
    fuelCapacity: "6,325 gal",
    takeoffDistance: "5,900 ft",
    landingDistance: "2,776 ft",
    amenities: [
      "WiFi",
      "Satellite Phone",
      "Full Galley",
      "Private Lavatory",
      "Lie-flat Seats",
      "Entertainment System",
      "Power Outlets",
    ],
    notes: "WiFi available. Premium interior configuration. Gogo ATG-5000.",
    tripStats: {
      totalTrips: 12,
      thisYear: 12,
      avgUtilization: "68%",
    },
    maintenanceSchedule: [
      { label: "Last 100-Hour Inspection", date: "2026-07-15", status: "Completed" },
      { label: "Last Annual", date: "2026-01-20", status: "Completed" },
      { label: "Next 100-Hour Due", date: "2026-09-15", status: "Scheduled" },
    ],
    tripHistory: [
      {
        tripId: "#TJ-1048",
        broker: "Benny",
        route: "KTEB → KPBI",
        departure: "Aug 15, 2026",
        returnDate: "Aug 18, 2026",
        operator: "Jet Aviation",
        aircraftType: "Challenger 350",
        status: "Confirmed",
      },
      {
        tripId: "TJ-2402",
        broker: "Benny",
        route: "KTEB → KMIA",
        departure: "Aug 20, 2026",
        returnDate: "Aug 23, 2026",
        operator: "Air Charter Group",
        aircraftType: "Gulfstream G450",
        status: "Booked",
      },
      {
        tripId: "TJ-2403",
        broker: "Mark",
        route: "KMIA → EGLL",
        departure: "Sep 3, 2026",
        returnDate: "Sep 10, 2026",
        operator: "VistaJet",
        aircraftType: "Global 7500",
        status: "Booked",
      },
      {
        tripId: "TJ-2403",
        broker: "Mark",
        route: "KMIA → EGLL",
        departure: "Sep 3, 2026",
        returnDate: "Sep 10, 2026",
        operator: "VistaJet",
        aircraftType: "Global 7500",
        status: "Booked",
      },
      {
        tripId: "TJ-2403",
        broker: "Mark",
        route: "KMIA → EGLL",
        departure: "Sep 3, 2026",
        returnDate: "Sep 10, 2026",
        operator: "VistaJet",
        aircraftType: "Global 7500",
        status: "Booked",
      },
      {
        tripId: "TJ-2404",
        broker: "Benny",
        route: "KVNY → KASE",
        departure: "Aug 20, 2026",
        returnDate: "---",
        operator: "Rocky Mountain Air",
        aircraftType: "Citation CJ3+",
        status: "Confirmed",
      },
    ],
  },
  {
    id: "AC-1002",
    model: "Global 7500",
    tail: "N785EX",
    category: "Ultra Long Range",
    operator: "FlexJet",
    operatorId: "OP-1001",
    capacity: "16 pax",
    paxCount: 16,
    rangeNm: "7,700",
    rangeNum: 7700,
    year: 2021,
    status: "Available",
    trips: 18,
    homeBase: "Teterboro (KTEB)",
    registration: "N785EX",
    manufacturer: "Bombardier Aerospace",
    modelYear: "2021",
    maxPassengers: "16",
    maxRange: "7,700 nm",
    maxSpeed: "Mach 0.925",
    cruiseSpeed: "Mach 0.85",
    serviceCeiling: "51,000 ft",
    baggageCapacity: "195 cu ft",
    cabinLength: "54.4 ft",
    maxTakeoffWeight: "114,850 lb",
    emptyWeight: "61,700 lb",
    fuelCapacity: "7,500 gal",
    takeoffDistance: "5,800 ft",
    landingDistance: "2,520 ft",
    amenities: [
      "Ka-band High Speed WiFi",
      "Satellite Phone",
      "Full Galley",
      "Private Lavatory",
      "Master Suite",
      "Power Outlets",
    ],
    notes: "Flagship ultra-long range jet with Ka-band high-speed internet and four living zones.",
    tripStats: {
      totalTrips: 18,
      thisYear: 18,
      avgUtilization: "74%",
    },
    maintenanceSchedule: [
      { label: "Last 100-Hour Inspection", date: "2026-08-01", status: "Completed" },
      { label: "Last Annual", date: "2026-02-10", status: "Completed" },
      { label: "Next 100-Hour Due", date: "2026-10-01", status: "Scheduled" },
    ],
    tripHistory: [],
  },
  {
    id: "AC-1003",
    model: "Challenger 350",
    tail: "N680EX",
    category: "Super Midsize",
    operator: "FlexJet",
    operatorId: "OP-1001",
    capacity: "9 pax",
    paxCount: 9,
    rangeNm: "3,500",
    rangeNum: 3500,
    year: 2020,
    status: "Available",
    trips: 22,
    homeBase: "Van Nuys (KVNY)",
    registration: "N680EX",
    manufacturer: "Bombardier Aerospace",
    modelYear: "2020",
    maxPassengers: "9",
    maxRange: "3,500 nm",
    maxSpeed: "Mach 0.83",
    cruiseSpeed: "Mach 0.80",
    serviceCeiling: "45,000 ft",
    baggageCapacity: "106 cu ft",
    cabinLength: "25.2 ft",
    maxTakeoffWeight: "40,600 lb",
    emptyWeight: "24,800 lb",
    fuelCapacity: "2,100 gal",
    takeoffDistance: "4,835 ft",
    landingDistance: "2,364 ft",
    amenities: ["WiFi", "Full Galley", "Private Lavatory", "Power Outlets"],
    notes: "Best-selling super-midsize with coast-to-coast US capability.",
    tripStats: {
      totalTrips: 22,
      thisYear: 22,
      avgUtilization: "71%",
    },
    maintenanceSchedule: [
      { label: "Last 100-Hour Inspection", date: "2026-07-20", status: "Completed" },
      { label: "Last Annual", date: "2026-03-15", status: "Completed" },
      { label: "Next 100-Hour Due", date: "2026-09-20", status: "Scheduled" },
    ],
    tripHistory: [],
  },
];
