export const airportCountryOptions = [
  "All Countries",
  "USA",
  "United Kingdom",
  "France",
  "Switzerland",
  "Canada",
];

export const airportStats = [
  { label: "TOTAL AIRPORTS", value: 10 },
  { label: "DOMESTIC", value: 8 },
  { label: "INTERNATIONAL", value: 2, tone: "purple" },
  { label: "WITH ASSIGNED FBO", value: 10, tone: "success" },
];

export const airportsData = [
  {
    id: "APT-1001",
    icao: "KTEB",
    iata: "TEB",
    name: "Teterboro Airport",
    city: "Teterboro",
    state: "NJ",
    country: "USA",
    latitude: "40.8508",
    longitude: "-74.0613",
    assignedFbo: "Signature Flight Support",
    notes: "Primary departure airport for NYC clients.",
  },
  {
    id: "APT-1002",
    icao: "KPBI",
    iata: "PBI",
    name: "Palm Beach International",
    city: "West Palm Beach",
    state: "FL",
    country: "USA",
    latitude: "26.6832",
    longitude: "-80.0956",
    assignedFbo: "Atlantic Aviation",
    notes: "Key winter hub for South Florida private aviation traffic.",
  },
  {
    id: "APT-1003",
    icao: "KMIA",
    iata: "MIA",
    name: "Miami International",
    city: "Miami",
    state: "FL",
    country: "USA",
    latitude: "25.7959",
    longitude: "-80.2870",
    assignedFbo: "Signature Aviation",
    notes: "Heavy commercial and cargo traffic; prefer KOPF for light jets.",
  },
  {
    id: "APT-1004",
    icao: "KLAS",
    iata: "LAS",
    name: "Harry Reid International",
    city: "Las Vegas",
    state: "NV",
    country: "USA",
    latitude: "36.0840",
    longitude: "-115.1537",
    assignedFbo: "Signature Flight Support",
    notes: "High traffic during major conventions and events.",
  },
  {
    id: "APT-1005",
    icao: "KVNY",
    iata: "VNY",
    name: "Van Nuys Airport",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
    latitude: "34.2098",
    longitude: "-118.4899",
    assignedFbo: "Castle & Cooke Aviation",
    notes: "World's busiest dedicated general aviation airport.",
  },
  {
    id: "APT-1006",
    icao: "KASE",
    iata: "ASE",
    name: "Aspen/Pitkin County",
    city: "Aspen",
    state: "CO",
    country: "USA",
    latitude: "39.2232",
    longitude: "-106.8688",
    assignedFbo: "Atlantic Aviation",
    notes: "High altitude mountain airport with strict curfew.",
  },
  {
    id: "APT-1007",
    icao: "KLAX",
    iata: "LAX",
    name: "Los Angeles International",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
    latitude: "33.9416",
    longitude: "-118.4085",
    assignedFbo: "Atlantic Aviation",
    notes: "Major West Coast international gateway.",
  },
  {
    id: "APT-1008",
    icao: "KJFK",
    iata: "JFK",
    name: "John F. Kennedy Intl",
    city: "New York",
    state: "NY",
    country: "USA",
    latitude: "40.6413",
    longitude: "-73.7781",
    assignedFbo: "Sheltair Aviation",
    notes: "Slot controlled during afternoon peak hours.",
  },
  {
    id: "APT-1009",
    icao: "EGLL",
    iata: "LHR",
    name: "London Heathrow Airport",
    city: "London",
    state: "ENG",
    country: "United Kingdom",
    latitude: "51.4700",
    longitude: "-0.4543",
    assignedFbo: "Signature Flight Support",
    notes: "Slot controlled. 24/7 UK Border Force available.",
  },
  {
    id: "APT-1010",
    icao: "LFPB",
    iata: "LBG",
    name: "Paris Le Bourget",
    city: "Paris",
    state: "IDF",
    country: "France",
    latitude: "48.9694",
    longitude: "2.4414",
    assignedFbo: "Jetex Paris Le Bourget",
    notes: "Premier private aviation airport serving Paris.",
  },
];
