export const clientStats = [
  { label: "Total Clients", value: "16", meta: "in database", tone: "foreground" },
  { label: "Active & VIP", value: "12", meta: "75% of total", tone: "info" },
  { label: "Follow-ups Due", value: "5", meta: "overdue or today", tone: "destructive" },
  { label: "Added in 2026", value: "3", meta: "new this year", tone: "success" },
];

export const clientStatusOptions = ["All Statuses", "Active", "Inactive", "Lead", "VIP"];
export const clientTypeOptions = ["All Types", "Direct", "Travel Agent", "Referral", "Corporate"];
export const clientBrokerOptions = ["All Brokers", "Barry", "Benny", "Mark", "Ari"];
export const clientFollowUpOptions = ["All Follow-ups", "Due Today", "Overdue", "Upcoming"];

export const clientsData = [
  {
    id: "CL-1001",
    name: "Hope Sterling",
    company: "Sterling Group",
    type: "Direct",
    email: "hope.sterling@sterlinggroup.com",
    phone: "+1 (212) 555-0184",
    prefAirports: "KTEB → KMIA",
    homeAirport: "KTEB",
    preferredAirports: ["KTEB", "KMIA"],
    preferredRoutes: ["KTEB → KMIA"],
    preferredAircraft: ["Gulfstream G550", "Global 6000"],
    lastTripId: "#TJ-1048",
    lastTripDate: "Aug 15, 2026",
    nextFollowUpDate: "Aug 15, 2026",
    nextFollowUpStatus: "Upcoming", // "Upcoming", "Due Today", "Overdue"
    status: "VIP", // "VIP", "Active", "Quoted", "Lead", "Inactive"
    broker: "Benny",
    leadSource: "Referral",
    addedDate: "Jan 2026",
    totalTrips: 18,
    tripsOnRecord: 6,
    totalSpent: "$485,000",
    totalSpentRaw: 485000,
    activeQuotesCount: 1,
    notes: "Hope prefers morning departures. Always book catering — seafood preferred. Send itinerary PDF 48 hours prior. Strongly prefers ExecuJet as operator. Birthday: March 14.",
    followUpNote: "Check availability for Miami → New York round trip in September",
  },
  {
    id: "CL-1002",
    name: "Mike Anderson",
    company: "Anderson Ventures",
    type: "Direct",
    email: "m.anderson@andersonventures.com",
    phone: "+1 (310) 555-0291",
    prefAirports: "KTEB → KTEB",
    homeAirport: "KTEB",
    preferredAirports: ["KTEB"],
    preferredRoutes: ["KTEB → KTEB"],
    preferredAircraft: ["Citation XLS"],
    lastTripId: "#TJ-1045",
    lastTripDate: "Aug 12, 2026",
    nextFollowUpDate: "Aug 11, 2026",
    nextFollowUpStatus: "Due Today",
    status: "Active",
    broker: "Barry",
    leadSource: "Direct",
    addedDate: "Feb 2026",
    totalTrips: 8,
    tripsOnRecord: 4,
    totalSpent: "$195,000",
    totalSpentRaw: 195000,
    activeQuotesCount: 1,
    notes: "Prefers mid-size jets with high-speed Wi-Fi.",
    followUpNote: "Send quote for Teterboro round trip",
  },
  {
    id: "CL-1003",
    name: "Sarah Chen",
    company: "",
    type: "Direct",
    email: "sarah.chen@icloud.com",
    phone: "+1 (415) 555-0318",
    prefAirports: "KJFK → KMIA",
    homeAirport: "KJFK",
    preferredAirports: ["KJFK", "KMIA"],
    preferredRoutes: ["KJFK → KMIA"],
    preferredAircraft: ["Challenger 350"],
    lastTripId: "#TJ-1046",
    lastTripDate: "Aug 14, 2026",
    nextFollowUpDate: "",
    nextFollowUpStatus: "",
    status: "Active",
    broker: "Mark",
    leadSource: "Web Search",
    addedDate: "Mar 2026",
    totalTrips: 5,
    tripsOnRecord: 3,
    totalSpent: "$142,000",
    totalSpentRaw: 142000,
    activeQuotesCount: 0,
    notes: "Prefers pet-friendly flights.",
    followUpNote: "",
  },
  {
    id: "CL-1004",
    name: "Robert Walsh",
    company: "Walsh Capital",
    type: "Direct",
    email: "rwalsh@walshcapital.com",
    phone: "+1 (212) 555-0442",
    prefAirports: "KTEB → KPBI",
    homeAirport: "KTEB",
    preferredAirports: ["KTEB", "KPBI"],
    preferredRoutes: ["KTEB → KPBI"],
    preferredAircraft: ["Gulfstream G450"],
    lastTripId: "#TJ-1047",
    lastTripDate: "Aug 16, 2026",
    nextFollowUpDate: "Aug 9, 2026",
    nextFollowUpStatus: "Overdue",
    status: "Active",
    broker: "Barry",
    leadSource: "Referral",
    addedDate: "Jan 2026",
    totalTrips: 12,
    tripsOnRecord: 5,
    totalSpent: "$310,000",
    totalSpentRaw: 310000,
    activeQuotesCount: 2,
    notes: "Requires ground transport arranged on arrival.",
    followUpNote: "Follow up on Palm Beach winter schedule",
  },
  {
    id: "CL-1005",
    name: "David Park",
    company: "Park Investments",
    type: "Direct",
    email: "david.park@parkinvestments.com",
    phone: "+1 (312) 555-0527",
    prefAirports: "KORD → KTEB",
    homeAirport: "KORD",
    preferredAirports: ["KORD", "KTEB"],
    preferredRoutes: ["KORD → KTEB"],
    preferredAircraft: ["Falcon 2000EX"],
    lastTripId: "#TJ-1049",
    lastTripDate: "Aug 18, 2026",
    nextFollowUpDate: "Aug 15, 2026",
    nextFollowUpStatus: "Upcoming",
    status: "Active",
    broker: "Mark",
    leadSource: "Corporate",
    addedDate: "Apr 2026",
    totalTrips: 6,
    tripsOnRecord: 3,
    totalSpent: "$168,000",
    totalSpentRaw: 168000,
    activeQuotesCount: 0,
    notes: "Strict timing for business meetings.",
    followUpNote: "Confirm Chicago departure slot",
  },
  {
    id: "CL-1006",
    name: "James Kellner",
    company: "Kellner Holdings",
    type: "Direct",
    email: "j.kellner@kellnerholdings.com",
    phone: "+1 (702) 555-0638",
    prefAirports: "KTEB → KLAS",
    homeAirport: "KTEB",
    preferredAirports: ["KTEB", "KLAS"],
    preferredRoutes: ["KTEB → KLAS"],
    preferredAircraft: ["Global 7500"],
    lastTripId: "#TJ-1050",
    lastTripDate: "Aug 20, 2026",
    nextFollowUpDate: "",
    nextFollowUpStatus: "",
    status: "VIP",
    broker: "Barry",
    leadSource: "Referral",
    addedDate: "Nov 2025",
    totalTrips: 22,
    tripsOnRecord: 7,
    totalSpent: "$620,000",
    totalSpentRaw: 620000,
    activeQuotesCount: 1,
    notes: "High value VIP client. Custom wine list required.",
    followUpNote: "",
  },
  {
    id: "CL-1007",
    name: "Amanda Torres",
    company: "Torres Real Estate",
    type: "Direct",
    email: "amanda.t@torresre.com",
    phone: "+1 (305) 555-0741",
    prefAirports: "KMIA → KLAX",
    homeAirport: "KMIA",
    preferredAirports: ["KMIA", "KLAX"],
    preferredRoutes: ["KMIA → KLAX"],
    preferredAircraft: ["Challenger 605"],
    lastTripId: "#TJ-1042",
    lastTripDate: "Jul 28, 2026",
    nextFollowUpDate: "Aug 10, 2026",
    nextFollowUpStatus: "Due Today",
    status: "Active",
    broker: "Benny",
    leadSource: "Web Search",
    addedDate: "May 2026",
    totalTrips: 4,
    tripsOnRecord: 2,
    totalSpent: "$98,000",
    totalSpentRaw: 98000,
    activeQuotesCount: 1,
    notes: "Prefers non-stop coast to coast flights.",
    followUpNote: "Send Miami to LAX quote options",
  },
  {
    id: "CL-1008",
    name: "Richard Bloom",
    company: "",
    type: "Direct",
    email: "rbloom@gmail.com",
    phone: "+1 (646) 555-0853",
    prefAirports: "KORD → KTEB",
    homeAirport: "KORD",
    preferredAirports: ["KORD", "KTEB"],
    preferredRoutes: ["KORD → KTEB"],
    preferredAircraft: ["Citation Latitude"],
    lastTripId: "#TJ-1038",
    lastTripDate: "Jul 10, 2026",
    nextFollowUpDate: "Aug 15, 2026",
    nextFollowUpStatus: "Upcoming",
    status: "Quoted",
    broker: "Ari",
    leadSource: "Referral",
    addedDate: "Jun 2026",
    totalTrips: 2,
    tripsOnRecord: 1,
    totalSpent: "$38,000",
    totalSpentRaw: 38000,
    activeQuotesCount: 1,
    notes: "Awaiting approval for summer trip.",
    followUpNote: "Check status of quote Q-2026-038",
  },
];

export const clientTripsHistory = [
  {
    id: "#TJ-1048",
    broker: "Benny",
    from: "KTEB",
    to: "KPBI",
    departure: "Aug 15, 2026",
    returnDate: "Aug 18, 2026",
    aircraftOperator: "Jet Aviation Challenger 350",
    status: "Confirmed",
    clientPmt: "Paid",
    fet: "$1,500",
    profit: "$8,500",
  },
  {
    id: "TJ-2402",
    broker: "Benny",
    from: "KTEB",
    to: "KMIA",
    departure: "Aug 20, 2026",
    returnDate: "Aug 23, 2026",
    aircraftOperator: "Air Charter G... Gulfstream G...",
    status: "Booked",
    clientPmt: "Partially Paid",
    fet: "$2,250",
    profit: "$17,000",
  },
  {
    id: "TJ-2403",
    broker: "Mark",
    from: "KMIA",
    to: "EGLL",
    departure: "Sep 3, 2026",
    returnDate: "Sep 10, 2026",
    aircraftOperator: "VistaJet Global 7500",
    status: "Booked",
    clientPmt: "Quoted",
    fet: "$2,775",
    profit: "$37,000",
  },
  {
    id: "TJ-2404",
    broker: "Benny",
    from: "KVNY",
    to: "KASE",
    departure: "Aug 20, 2026",
    returnDate: "---",
    aircraftOperator: "Rocky Mount... Citation CJ3+",
    status: "Confirmed",
    clientPmt: "Paid",
    fet: "$397",
    profit: "$5,300",
  },
];

export const clientQuotesHistory = [
  {
    quoteId: "Q-2026-042",
    from: "KTEB",
    to: "KPBI",
    amount: "$79,500",
    date: "Aug 8, 2026",
    status: "Sent",
  },
  {
    quoteId: "Q-2026-039",
    from: "KTEB",
    to: "KMIA",
    amount: "$42,500",
    date: "Aug 5, 2026",
    status: "Accepted",
  },
  {
    quoteId: "Q-2026-028",
    from: "KMIA",
    to: "EGLL",
    amount: "$36,000",
    date: "Jun 18, 2026",
    status: "Expired",
  },
];

export const clientPaymentsHistory = [
  {
    invoice: "INV-2026-108",
    trip: "TJ-1048",
    amount: "$79,500",
    paid: "$79,500",
    balance: "$0",
    status: "Paid",
    dueDate: "Aug 9, 2026",
  },
  {
    invoice: "INV-2026-097",
    trip: "TJ-1039",
    amount: "$42,500",
    paid: "$42,500",
    balance: "$0",
    status: "Paid",
    dueDate: "Jun 25, 2026",
  },
  {
    invoice: "INV-2026-071",
    trip: "TJ-1033",
    amount: "$36,000",
    paid: "$36,000",
    balance: "$0",
    status: "Paid",
    dueDate: "Apr 20, 2026",
  },
  {
    invoice: "INV-2026-029",
    trip: "TJ-1026",
    amount: "$36,000",
    paid: "$36,000",
    balance: "$0",
    status: "Paid",
    dueDate: "Feb 5, 2026",
  },
];

export const clientActivities = [
  {
    id: 1,
    user: "Barry",
    action: "confirmed TJ-1048 and sent final itinerary to Hope",
    time: "Aug 9 · 15:42",
    type: "confirm",
  },
  {
    id: 2,
    user: "ExecuJet",
    action: "operator confirmation received for TJ-1048",
    time: "Aug 9 · 14:20",
    type: "operator",
  },
  {
    id: 3,
    user: "Ari",
    action: "payment received — $42,500 cleared for TJ-1048",
    time: "Aug 8 · 17:35",
    type: "payment",
  },
  {
    id: 4,
    user: "Barry",
    action: "sent round trip quote Q-2026-042 ($79,500)",
    time: "Aug 8 · 11:00",
    type: "quote",
  },
];
