export const commissionsStats = [
  { label: "TOTAL COMMISSIONS", value: "$10,900", tone: "foreground" },
  { label: "PAID", value: "$7,900", tone: "success" },
  { label: "PENDING", value: "$3000", tone: "warning" },
  { label: "AVG COMMISSION", value: "$1,817", tone: "foreground" },
];

export const commissionsStatusFilterOptions = [
  "All Status",
  "Paid",
  "Partially Paid",
  "Overdue",
  "Due",
  "Pending",
  "Cancelled",
];

export const commissionsData = [
  {
    id: "COM-1001",
    recipient: "Sophia Morgan",
    tripId: "TJ-1051",
    amount: "$2,100",
    amountRaw: 2100,
    dated: "Aug 20, 2026",
    method: "Check",
    broker: "Barry",
    type: "CRM Client",
    status: "Paid",
    notes: "Referral commission for Miami trip",
  },
  {
    id: "COM-1002",
    recipient: "Daniel Brooks",
    tripId: "TJ-1052",
    amount: "$1,800",
    amountRaw: 1800,
    dated: "-",
    method: "Zelle",
    broker: "Mark",
    type: "CRM Client",
    status: "Pending",
    notes: "",
  },
  {
    id: "COM-1003",
    recipient: "Elite Travel Co.",
    company: "Elite Travel Co.",
    tripId: "TJ-1043",
    amount: "$2,500",
    amountRaw: 2500,
    dated: "Aug 10, 2026",
    method: "Wire Transfer",
    broker: "Mark",
    type: "Manual",
    status: "Paid",
    notes: "External agency partner commission",
  },
  {
    id: "COM-1004",
    recipient: "Hope Sterling",
    tripId: "TJ-1046",
    amount: "$1,800",
    amountRaw: 1800,
    dated: "Aug 16, 2026",
    method: "Check",
    broker: "Barry",
    type: "CRM Client",
    status: "Paid",
    notes: "",
  },
  {
    id: "COM-1005",
    recipient: "James Holloway",
    tripId: "TJ-1026",
    amount: "$1,200",
    amountRaw: 1200,
    dated: "Aug 9, 2026",
    method: "Wire Transfer",
    broker: "Mark",
    type: "Manual",
    status: "Paid",
    notes: "",
  },
  {
    id: "COM-1006",
    recipient: "Sarah Chen",
    tripId: "TJ-1026",
    amount: "$1,500",
    amountRaw: 1500,
    dated: "-",
    method: "Zelle",
    broker: "Mark",
    type: "CRM Client",
    status: "Pending",
    notes: "",
  },
];
