export const dashboardStatsRow1 = [
  {
    id: "stat-1",
    icon: "/dashboard/icons/stat1-icon.svg",
    spark: "/dashboard/icons/stat1-spark.svg",
    badgeText: "18% vs last week",
    tone: "success",
    title: "UPCOMING TRIPS",
    value: "14",
    subtitle: "Active on the board",
    subtitleTone: "muted",
  },
  {
    id: "stat-2",
    icon: "/dashboard/icons/stat2-icon.svg",
    spark: "/dashboard/icons/stat2-spark.svg",
    badgeText: "18% vs last week",
    tone: "success",
    title: "OPEN REQUESTS",
    value: "2",
    subtitle: "awaiting sourcing",
    subtitleTone: "warning",
  },
  {
    id: "stat-3",
    icon: "/dashboard/icons/stat3-icon.svg",
    spark: "/dashboard/icons/stat3-spark.svg",
    badgeText: "18% vs last week",
    tone: "success",
    title: "REVENUE (MTD)",
    value: "$284.5K",
    subtitle: "across all trips",
    subtitleTone: "success",
  },
  {
    id: "stat-4",
    icon: "/dashboard/icons/stat4-icon.svg",
    spark: "/dashboard/icons/stat4-spark.svg",
    badgeText: "18% vs last week",
    tone: "destructive",
    title: "GROSS PROFIT",
    value: "$38.2K",
    subtitle: "15.8% margin",
    subtitleTone: "destructive",
  },
];

export const dashboardStatsRow2 = [
  {
    id: "stat-5",
    icon: "/dashboard/icons/stat5-icon.svg",
    spark: "/dashboard/icons/stat5-spark.svg",
    badgeText: "3 overdue payments",
    tone: "warning",
    title: "UPCOMING TRIPS",
    value: "$280.8k",
    subtitle: "4 open invouces",
    subtitleTone: "warning",
  },
  {
    id: "stat-6",
    icon: "/dashboard/icons/stat6-icon.svg",
    spark: "/dashboard/icons/stat6-spark.svg",
    badgeText: "8 upcoming due",
    tone: "info",
    title: "OPERATOR PAYMENTS",
    value: "$280.8k",
    subtitle: "3 upcoming due",
    subtitleTone: "info",
  },
  {
    id: "stat-7",
    icon: "/dashboard/icons/stat7-icon.svg",
    spark: "/dashboard/icons/stat7-spark.svg",
    badgeText: "18% vs last week",
    tone: "warning",
    title: "FET COLLECTED",
    value: "$46.7k",
    subtitle: "7.5% of trip amounts",
    subtitleTone: "foreground",
  },
  {
    id: "stat-8",
    icon: "/dashboard/icons/stat8-icon.svg",
    spark: "/dashboard/icons/stat8-spark.svg",
    badgeText: "18% vs last week",
    tone: "purple",
    title: "Empty Leg Matches",
    value: "6 active",
    subtitle: "4 client matches",
    subtitleTone: "foreground",
  },
];

export const todaysPriorities = [
  {
    dot: "bg-destructive",
    status: "Due Today",
    category: "Follow-up",
    title: "Follow up with Hope Sterling re: Miami → NY quote",
    date: "Today",
    meta: "Hope Sterling",
    actions: ["Follow Up", "View"],
  },
  {
    dot: "bg-destructive",
    status: "Overdue",
    category: "Payment",
    title: "Client payment overdue — Trip #TJ-1048",
    date: "3 days ago",
    meta: "Trip #TJ-1048",
    actions: ["View", "Send Reminder"],
  },
  {
    dot: "bg-warning",
    status: "Pending",
    category: "Payment",
    title: "VistaJet operator payment due tomorrow",
    date: "Tomorrow",
    meta: "VistaJet",
    actions: ["View", "Mark Paid"],
  },
  {
    dot: "bg-warning",
    status: "Pending",
    category: "Confirmation",
    title: "Confirm itinerary for Mike Anderson — Aug 12 trip",
    date: "Aug 11",
    meta: "Trip #TJ-1045",
    actions: ["Open Trip"],
    markComplete: true,
  },
  {
    dot: "bg-warning",
    status: "Pending",
    category: "Empty Leg",
    title: "Empty leg match available — Miami → Teterboro",
    date: "Aug 12",
    meta: "3 Client Matches",
    actions: ["View Match"],
  },
];

export const emptyLegOpportunities = [
  {
    id: "el-1",
    route: "Miami → Teterboro",
    aircraft: "Challenger 605 · VistaJet",
    date: "Aug 12",
    matches: "3 client matches",
    matchTone: "text-success",
  },
  {
    id: "el-2",
    route: "Fort Lauderdale → Teterboro",
    aircraft: "Citation XLS · NetJets",
    date: "Aug 14",
    matches: "1 client match",
    matchTone: "text-warning",
  },
  {
    id: "el-3",
    route: "Fort Lauderdale → Teterboro",
    aircraft: "Citation XLS · NetJets",
    date: "Aug 14",
    matches: "1 client match",
    matchTone: "text-warning",
  },
  {
    id: "el-4",
    route: "Los Angeles → Miami",
    aircraft: "Gulfstream G450 · ExecuJet",
    date: "Aug 16",
    matches: "2 client matches",
    matchTone: "text-info",
  },
];

export const recentActivities = [
  { id: "act-1", name: "Barry", action: "created", subject: "Trip #TJ-1050", time: "2h ago" },
  { id: "act-2", name: "Ari", action: "marked client payment received for", subject: "Mike Anderson", time: "4h ago" },
  { id: "act-3", name: "Mark", action: "created a quote for", subject: "David Park", time: "Yesterday" },
  { id: "act-4", name: "Benny", action: "updated operator profile —", subject: "ExecuJet", time: "Yesterday" },
  { id: "act-5", name: "Barry", action: "uploaded itinerary for", subject: "Trip #TJ-1045", time: "2 days ago" },
  { id: "act-6", name: "System", action: "matched empty leg to 3 clients —", subject: "Miami → Teterboro", time: "2 days ago" },
];

export const upcomingFollowUps = [
  { id: "fu-1", dot: "bg-warning", name: "Hope Sterling", status: "Due Today", note: "Miami → NY quote follow-up", date: "Today", owner: "Barry" },
  { id: "fu-2", dot: "bg-warning", name: "Hope Sterling", status: "Due Today", note: "Miami → NY quote follow-up", date: "Today", owner: "Barry" },
  { id: "fu-3", dot: "bg-muted-foreground", name: "Mike Anderson", status: "Pending", note: "Aug 12 charter confirmation", date: "Aug 11", owner: "Barry" },
  { id: "fu-4", dot: "bg-muted-foreground", name: "Mike Anderson", status: "Pending", note: "Aug 12 charter confirmation", date: "Aug 11", owner: "Barry" },
  { id: "fu-5", dot: "bg-muted-foreground", name: "Sarah Chen", status: "Pending", note: "Re-booking after itinerary change", date: "Aug 13", owner: "Benny" },
];

export const financialReceivables = [
  { id: "rec-1", name: "Hope Sterling", meta: "#TJ-1048 · Due Aug 6, 2026", amount: "$22,000", status: "Overdue" },
  { id: "rec-2", name: "Sarah Chen", meta: "#TJ-1046 · Due Aug 16, 2026", amount: "$8,200", status: "Partially Paid" },
  { id: "rec-3", name: "Robert Walsh", meta: "#TJ-1047 · Due Aug 15, 2026", amount: "$12,800", status: "Pending" },
  { id: "rec-4", name: "Mike Anderson", meta: "#TJ-1045 · Due Aug 5, 2026", amount: "$18,500", status: "Paid" },
];

export const financialPayments = [
  { id: "pay-1", name: "VistaJet", meta: "#TJ-1045 · Due Aug 10, 2026", amount: "$14,800", status: "Due Soon" },
  { id: "pay-2", name: "NetJets", meta: "#TJ-1046 · Due Aug 16, 2026", amount: "$6,400", status: "Pending" },
  { id: "pay-3", name: "Wheels Up", meta: "#TJ-1047 · Due Aug 18, 2026", amount: "$9,100", status: "Pending" },
  { id: "pay-4", name: "ExecuJet", meta: "#TJ-1048 · Due Aug 8, 2026", amount: "$12,200", status: "Paid" },
];

export const upcomingDashboardTrips = [
  {
    trip: "#TJ-1048",
    date: "Aug 9, 2026",
    client: "Hope Sterling",
    broker: "Benny",
    route: "Miami → Los Angeles",
    aircraft: "Gulfstream G550",
    operator: "ExecuJet",
    status: "Confirmed",
    clientPmt: "Overdue",
    opPmt: "Paid",
    profit: "$14,500",
  },
  {
    trip: "#TJ-1046",
    date: "Aug 14, 2026",
    client: "Sarah Chen",
    broker: "Mark",
    route: "New York → Miami",
    aircraft: "Citation XLS",
    operator: "NetJets",
    status: "Confirmed",
    clientPmt: "Partially Paid",
    opPmt: "Pending",
    profit: "$2,800",
  },
  {
    trip: "#TJ-1047",
    date: "Aug 16, 2026",
    client: "Robert Walsh",
    broker: "Barry",
    route: "Teterboro → Palm Beach",
    aircraft: "King Air 350",
    operator: "Wheels Up",
    status: "Pending",
    clientPmt: "Pending",
    opPmt: "Pending",
    profit: "$1,800",
  },
  {
    trip: "#TJ-1049",
    date: "Aug 18, 2026",
    client: "David Park",
    broker: "Mark",
    route: "Chicago → Teterboro",
    aircraft: "Phenom 300",
    operator: "Flexjet",
    status: "Confirmed",
    clientPmt: "Paid",
    opPmt: "Paid",
    profit: "$3,200",
  },
  {
    trip: "#TJ-1050",
    date: "Aug 20, 2026",
    client: "James Kellner",
    broker: "Barry",
    route: "Teterboro → Las Vegas",
    aircraft: "Global 6000",
    operator: "VistaJet",
    status: "Pending",
    clientPmt: "Pending",
    opPmt: "Pending",
    profit: "$8,900",
  },
];
