export const flightTrackingStats = [
  { label: "Active Flights", value: "4", tone: "warning" },
  { label: "On Time Rate", value: "96.5%", tone: "success" },
  { label: "Completed Today", value: "8", tone: "info" },
  { label: "Active Airports", value: "14", tone: "foreground" },
];

export const flightStatusFilterOptions = ["All", "In Flight", "Not Departed", "Delayed", "Completed"];

export const flightsData = [
  {
    id: "TJ-1040",
    tripId: "TJ-1040",
    client: "James Holloway",
    tailNumber: "N1040TJ",
    aircraft: "Global 7500",
    operator: "Flexjet",
    origin: "KTEB",
    destination: "KMIA",
    departureTime: "22:00",
    departureDate: "Aug 24, 2026",
    etaTime: "01:15",
    flightStatus: "Not Departed", // "In Flight", "Not Departed", "Delayed", "Completed"
    tripStatus: "Requested", // "Booked", "Requested", "Completed", etc.
    progressPercentage: 100,
    progressLabel: "Not in Flight",
    updates: [
      { text: "Flight confirmed by operator", time: "Aug 12, 3:45 PM" },
      { text: "Aircraft assigned: N1040TJ", time: "Aug 12, 4:00 PM" },
      { text: "Awaiting departure clearance", time: "Aug 15, 9:30 AM" },
    ],
  },
  {
    id: "TJ-2401",
    tripId: "#TJ-2401",
    client: "Eleanor Vance",
    tailNumber: "N1040TJ",
    aircraft: "Challenger 350",
    operator: "Flexjet",
    origin: "KTEB",
    destination: "KMIA",
    departureTime: "22:00",
    departureDate: "Aug 24, 2026 • 22:00",
    etaTime: "01:15",
    flightStatus: "In Flight",
    tripStatus: "Booked",
    progressPercentage: 65,
    progressLabel: "En Route - Alt 41,000 ft",
    updates: [
      { text: "Flight departure confirmed", time: "Aug 24, 10:05 PM" },
      { text: "Cruising altitude 41,000 ft reached", time: "Aug 24, 10:22 PM" },
      { text: "Estimated arrival at KMIA: 01:15 AM", time: "Aug 24, 10:45 PM" },
    ],
  },
  {
    id: "TJ-2402",
    tripId: "#TJ-2402",
    client: "Marcus Vance",
    tailNumber: "N1050TJ",
    aircraft: "Gulfstream G450",
    operator: "NetJets",
    origin: "VNY",
    destination: "KTEB",
    departureTime: "18:30",
    departureDate: "Aug 24, 2026 • 18:30",
    etaTime: "23:45",
    flightStatus: "Delayed",
    tripStatus: "Booked",
    progressPercentage: 15,
    progressLabel: "Ground Delay - Weather",
    updates: [
      { text: "Pre-flight checks complete", time: "Aug 24, 5:45 PM" },
      { text: "30-min ground hold issued at VNY (Weather)", time: "Aug 24, 6:15 PM" },
      { text: "Revised departure window: 19:00", time: "Aug 24, 6:30 PM" },
    ],
  },
  {
    id: "TJ-2403",
    tripId: "#TJ-2403",
    client: "Sophia Lin",
    tailNumber: "N1030TJ",
    aircraft: "Gulfstream G450",
    operator: "Air Charter Group",
    origin: "KTEB",
    destination: "KPBI",
    departureTime: "11:45",
    departureDate: "Aug 24, 2026 • 22:00",
    etaTime: "14:15",
    flightStatus: "Not Departed",
    tripStatus: "Booked",
    progressPercentage: 0,
    progressLabel: "Scheduled for Departure",
    updates: [
      { text: "Itinerary confirmed & dispatched", time: "Aug 24, 9:00 AM" },
      { text: "FBO handling confirmed at KTEB Signature", time: "Aug 24, 10:15 AM" },
    ],
  },
  {
    id: "TJ-2405",
    tripId: "#TJ-2405",
    client: "Hope Sterling",
    tailNumber: "N1020TJ",
    aircraft: "Global 7500",
    operator: "VistaJet",
    origin: "KTEB",
    destination: "KPBI",
    departureTime: "22:00",
    departureDate: "Aug 24, 2026 • 22:00",
    etaTime: "00:45",
    flightStatus: "Not Departed",
    tripStatus: "Booked",
    progressPercentage: 0,
    progressLabel: "Scheduled",
    updates: [
      { text: "Crew assigned by VistaJet", time: "Aug 24, 2:00 PM" },
      { text: "Catering requested & verified", time: "Aug 24, 4:30 PM" },
    ],
  },
  {
    id: "TJ-2390",
    tripId: "#TJ-2390",
    client: "David Chen",
    tailNumber: "N1080TJ",
    aircraft: "Phenom 300",
    operator: "Pacific Charter",
    origin: "KLAX",
    destination: "KSFO",
    departureTime: "08:00",
    departureDate: "Aug 24, 2026 • 08:00",
    etaTime: "09:15",
    flightStatus: "Completed",
    tripStatus: "Completed",
    progressPercentage: 100,
    progressLabel: "Landed & Parked",
    updates: [
      { text: "Landed safely at KSFO", time: "Aug 24, 9:12 AM" },
      { text: "Passengers deplaned at Landmark Aviation", time: "Aug 24, 9:20 AM" },
    ],
  },
];
