export const itinerariesStats = [
  { label: "TOTAL ITINERARIES", value: "5", tone: "foreground" },
  { label: "CONFIRMED", value: "1", tone: "success" },
  { label: "PENDING UPLOAD", value: "3", tone: "warning" },
  { label: "AWAITING CONFIRMATION", value: "1", tone: "purple" },
];

export const itinerariesData = [
  {
    id: "#TJ-1048",
    tripId: "TJ-1048",
    client: "Jonathan Reed",
    quoteNumber: "TJ-2026-0001",
    from: "KTEB",
    to: "KPBI",
    departure: "Aug 24, 2026 • 22:00",
    departureDate: "Aug 24",
    departureTime: "10:00 AM",
    arrivalTime: "12:45 PM",
    passengersCount: "2 pax",
    tailNumber: "N1040TJ",
    confirmed: "Yes", // "Yes" or "NO"
    tripStatus: "Confirmed",
    aircraft: "Global 7500",
    operator: "Flexjet",
    passengers: [
      { name: "Hope Sterling", passport: "P-8839201", initials: "HS" },
      { name: "James Sterling", passport: "P-8839202", initials: "JS" },
    ],
    catering: "Seafood Premium",
    groundTransport: "Mercedes S-Class",
    fbo: "Signature Flight Support",
    notes: "Internal notes visible to brokers only...",
  },
  {
    id: "#TJ-2402",
    tripId: "TJ-2402",
    client: "Hope Sterling",
    quoteNumber: "TJ-2026-0002",
    from: "KTEB",
    to: "KMIA",
    departure: "Aug 24, 2026 • 22:00",
    departureDate: "Aug 24",
    departureTime: "08:30 AM",
    arrivalTime: "11:15 AM",
    passengersCount: "3 pax",
    tailNumber: "N1050TJ",
    confirmed: "NO",
    tripStatus: "Booked",
    aircraft: "Challenger 350",
    operator: "Jet Aviation",
    passengers: [
      { name: "Hope Sterling", passport: "P-8839201", initials: "HS" },
      { name: "Eleanor Vance", passport: "P-8839203", initials: "EV" },
      { name: "Marcus Vance", passport: "P-8839204", initials: "MV" },
    ],
    catering: "Continental Breakfast & Champagne",
    groundTransport: "Cadillac Escalade ESV",
    fbo: "Atlantic Aviation",
    notes: "VIP handling requested at FBO.",
  },
  {
    id: "#TJ-2403",
    tripId: "TJ-2403",
    client: "Emily Carter",
    quoteNumber: "TJ-2026-0003",
    from: "KMIA",
    to: "EGLL",
    departure: "Aug 24, 2026 • 22:00",
    departureDate: "Aug 24",
    departureTime: "06:00 PM",
    arrivalTime: "07:30 AM +1",
    passengersCount: "2 pax",
    tailNumber: "N1070TJ",
    confirmed: "NO",
    tripStatus: "In Flight",
    aircraft: "Global 7500",
    operator: "VistaJet",
    passengers: [
      { name: "Emily Carter", passport: "P-9912044", initials: "EC" },
      { name: "Daniel Brooks", passport: "P-9912045", initials: "DB" },
    ],
    catering: "Fine Dining 3-Course Menu",
    groundTransport: "Rolls-Royce Phantom",
    fbo: "Signature Flight Support London",
    notes: "Transatlantic customs pre-cleared.",
  },
  {
    id: "#TJ-2404",
    tripId: "TJ-2404",
    client: "Robert Walsh",
    quoteNumber: "TJ-2026-0004",
    from: "KTEB",
    to: "KPBI",
    departure: "Aug 24, 2026 • 22:00",
    departureDate: "Aug 24",
    departureTime: "02:00 PM",
    arrivalTime: "04:45 PM",
    passengersCount: "4 pax",
    tailNumber: "N1030TJ",
    confirmed: "NO",
    tripStatus: "Booked",
    aircraft: "Gulfstream G450",
    operator: "Air Charter Group",
    passengers: [
      { name: "Robert Walsh", passport: "P-7740112", initials: "RW" },
      { name: "Sarah Walsh", passport: "P-7740113", initials: "SW" },
      { name: "Michael Walsh", passport: "P-7740114", initials: "MW" },
      { name: "Chloe Walsh", passport: "P-7740115", initials: "CW" },
    ],
    catering: "Gourmet Wine & Cheese Platter",
    groundTransport: "Executive SUV",
    fbo: "Jet Aviation Palm Beach",
    notes: "Pet on board - Dog approval confirmed.",
  },
  {
    id: "#TJ-2405",
    tripId: "TJ-2405",
    client: "Hope Sterling",
    quoteNumber: "TJ-2026-0005",
    from: "KTEB",
    to: "KPBI",
    departure: "Aug 24, 2026 • 22:00",
    departureDate: "Aug 24",
    departureTime: "09:00 PM",
    arrivalTime: "11:45 PM",
    passengersCount: "4 pax",
    tailNumber: "N1020TJ",
    confirmed: "NO",
    tripStatus: "Booked",
    aircraft: "Global 6000",
    operator: "Gama Aviation",
    passengers: [
      { name: "Hope Sterling", passport: "P-8839201", initials: "HS" },
      { name: "Alexis Reyes", passport: "P-8839209", initials: "AR" },
      { name: "Tyler Grant", passport: "P-8839210", initials: "TG" },
      { name: "David Chen", passport: "P-8839211", initials: "DC" },
    ],
    catering: "Sushi Selection & Fruit Platter",
    groundTransport: "Mercedes V-Class",
    fbo: "Signature Flight Support Teterboro",
    notes: "Late night arrival handling.",
  },
];
