export const leadsAgentsKPIStats = [
  { label: "Total Leads", value: "12", tone: "foreground" },
  { label: "New Leads", value: "3", tone: "foreground" },
  { label: "Follow-ups Due", value: "10", tone: "foreground" },
  { label: "Conversion Rate", value: "8%", tone: "foreground" },
  { label: "Active Agents", value: "4", tone: "foreground" },
];

export const agentStatusOptions = ["All Status", "Active", "Qualified", "Inactive"];
export const agentRoleOptions = ["All Roles", "Broker", "Senior Broker", "Admin", "Dispatcher"];

export const leadStatusOptions = [
  "All Status",
  "New",
  "Contacted",
  "Qualified",
  "Proposal",
  "Quoted",
  "Won",
  "Lost",
];

export const leadSourceOptions = [
  "All Sources",
  "Direct",
  "Referral",
  "Website",
  "Email",
  "Corporate",
];

export const leadBrokerOptions = ["All Brokers", "Barry", "Mark", "Benny", "Ari"];

export const leadPriorityOptions = ["All Priority", "High", "Medium", "Low"];

export const agentsData = [
  {
    id: "AGT-101",
    name: "Barry Wilson",
    email: "barry@tribecajets.com",
    phone: "+1 (212) 555-0201",
    company: "Sterling Group",
    contactEmail: "hope.sterling@sterlinggroup.com",
    contactPhone: "+1 (212) 555-0184",
    role: "Senior Broker",
    status: "Active",
    activeLeads: 4,
    qualifiedLeads: 6,
    convertedLeads: 22,
    activeTrips: 7,
    conversionRate: "68%",
    followUpsDue: 3,
    activePipeline: 4,
    maxLeadCapacity: 15,
    defaultFollowUp: "Call",
    permissionLevel: "Medium",
    workload: "Medium",
  },
  {
    id: "AGT-102",
    name: "Mark Evans",
    email: "mark@tribecajets.com",
    phone: "+1 (212) 555-0202",
    company: "Evans Aviation",
    contactEmail: "mark.evans@evansaviation.com",
    contactPhone: "+1 (212) 555-0202",
    role: "Broker",
    status: "Active",
    activeLeads: 3,
    qualifiedLeads: 5,
    convertedLeads: 18,
    activeTrips: 6,
    conversionRate: "54%",
    followUpsDue: 2,
    activePipeline: 3,
    maxLeadCapacity: 12,
    defaultFollowUp: "Email",
    permissionLevel: "Medium",
    workload: "Normal",
  },
  {
    id: "AGT-103",
    name: "Benny Carter",
    email: "benny@tribecajets.com",
    phone: "+1 (212) 555-0201",
    company: "Carter Air",
    contactEmail: "benny.carter@carterair.com",
    contactPhone: "+1 (212) 555-0201",
    role: "Broker",
    status: "Qualified",
    activeLeads: 3,
    qualifiedLeads: 4,
    convertedLeads: 15,
    activeTrips: 4,
    conversionRate: "61%",
    followUpsDue: 1,
    activePipeline: 3,
    maxLeadCapacity: 10,
    defaultFollowUp: "Call",
    permissionLevel: "Medium",
    workload: "Normal",
  },
  {
    id: "AGT-104",
    name: "Ari Wohl",
    email: "ari@tribecajets.com",
    phone: "+1 (212) 555-0203",
    company: "Tribeca Jets",
    contactEmail: "ari@tribecajets.com",
    contactPhone: "+1 (212) 555-0203",
    role: "Broker",
    status: "Qualified",
    activeLeads: 4,
    qualifiedLeads: 4,
    convertedLeads: 10,
    activeTrips: 3,
    conversionRate: "42%",
    followUpsDue: 4,
    activePipeline: 4,
    maxLeadCapacity: 12,
    defaultFollowUp: "WhatsApp",
    permissionLevel: "Admin",
    workload: "Medium",
  },
];

export const leadsData = [
  {
    id: "LD-201",
    name: "Jonathan Reed",
    company: "Reed Capital",
    email: "jonathan.reed@reedcapital.com",
    phone: "+1 (212) 555-0141",
    source: "Direct",
    origin: "TEB",
    destination: "MIA",
    route: "NYC → Miami",
    interest: "NYC → Miami, business charter…",
    priority: "High",
    broker: "Barry",
    brokerId: "AGT-101",
    nextFollowUp: "Aug 12, 2026",
    followUpTime: "10:00 AM",
    followUpMethod: "Call",
    status: "Proposal",
    createdDate: "Aug 8, 2026",
    departureAirport: "KTEB",
    destinationAirport: "KMIA",
    departureDate: "Aug 15, 2026",
    returnDate: "Aug 17, 2026",
    passengers: "4 pax",
    aircraftPreference: "Heavy Jet",
    tripNotes: "Needs catering and ground transport.",
    internalNotes: "High-value prospect. Referred by Hope Sterling.",
    estValue: "$28,000",
    activities: [
      {
        id: "LACT-1",
        title: "Lead created from direct inquiry",
        timestamp: "Aug 8, 2026 · 10:15",
        author: "System",
      },
      {
        id: "LACT-2",
        title: "Welcome email sent to jonathan.reed@reedcapital.com",
        timestamp: "Aug 8, 2026 · 11:00",
        author: "Barry",
      },
      {
        id: "LACT-3",
        title: "Proposal generated for TEB → MIA Heavy Jet",
        timestamp: "Aug 9, 2026 · 14:30",
        author: "Barry",
      },
    ],
    followUpsList: [
      {
        id: "LFU-1",
        title: "Aug 12, 2026 · Call",
        subtitle: "Assigned to Barry",
        status: "Upcoming",
      },
    ],
  },
  {
    id: "LD-202",
    name: "Emily Carter",
    company: "Carter Holdings",
    email: "emily.carter@carterholdings.com",
    phone: "+1 (305) 555-0192",
    source: "Website",
    origin: "TEB",
    destination: "MIA",
    route: "NYC → Miami",
    interest: "Family vacation to Miami",
    priority: "Medium",
    broker: "Benny",
    brokerId: "AGT-103",
    nextFollowUp: "Aug 14, 2026",
    followUpTime: "02:00 PM",
    followUpMethod: "Email",
    status: "Contacted",
    createdDate: "Aug 5, 2026",
    departureAirport: "KTEB",
    destinationAirport: "KMIA",
    departureDate: "Aug 20, 2026",
    returnDate: "Aug 25, 2026",
    passengers: "6 pax",
    aircraftPreference: "Midsize Jet",
    tripNotes: "Luggage requirements: 6 large bags.",
    internalNotes: "Previous client with sister charter company.",
    estValue: "$22,500",
    activities: [
      {
        id: "LACT-4",
        title: "Web inquiry submitted",
        timestamp: "Aug 5, 2026 · 09:12",
        author: "System",
      },
      {
        id: "LACT-5",
        title: "Introductory email sent",
        timestamp: "Aug 5, 2026 · 10:30",
        author: "Benny",
      },
    ],
    followUpsList: [
      {
        id: "LFU-2",
        title: "Aug 14, 2026 · Email",
        subtitle: "Assigned to Benny",
        status: "Upcoming",
      },
    ],
  },
  {
    id: "LD-203",
    name: "Daniel Brooks",
    company: "Brooks Group",
    email: "d.brooks@brooksgroup.com",
    phone: "+1 (424) 555-0178",
    source: "Direct",
    origin: "TEB",
    destination: "MIA",
    route: "NYC → Miami",
    interest: "Corporate board flight",
    priority: "High",
    broker: "Mark",
    brokerId: "AGT-102",
    nextFollowUp: "Aug 10, 2026",
    followUpTime: "11:30 AM",
    followUpMethod: "Call",
    status: "Qualified",
    createdDate: "Aug 3, 2026",
    departureAirport: "KTEB",
    destinationAirport: "KMIA",
    departureDate: "Aug 18, 2026",
    returnDate: "Aug 19, 2026",
    passengers: "8 pax",
    aircraftPreference: "Super Midsize",
    tripNotes: "Requires high-speed Wi-Fi onboard.",
    internalNotes: "Qualified lead, budget approved.",
    estValue: "$34,000",
    activities: [
      {
        id: "LACT-6",
        title: "Lead assigned to Mark",
        timestamp: "Aug 3, 2026 · 14:00",
        author: "System",
      },
    ],
    followUpsList: [
      {
        id: "LFU-3",
        title: "Aug 10, 2026 · Call",
        subtitle: "Assigned to Mark",
        status: "Upcoming",
      },
    ],
  },
  {
    id: "LD-204",
    name: "Sophia Morgan",
    company: "Morgan Ventures",
    email: "sophia.morgan@morganventures.com",
    phone: "+1 (646) 555-0165",
    source: "Email",
    origin: "TEB",
    destination: "MIA",
    route: "NYC → Miami",
    interest: "Weekend getaway",
    priority: "Low",
    broker: "Ari",
    brokerId: "AGT-104",
    nextFollowUp: "Aug 18, 2026",
    followUpTime: "04:00 PM",
    followUpMethod: "Email",
    status: "Proposal",
    createdDate: "Jul 28, 2026",
    departureAirport: "KTEB",
    destinationAirport: "KMIA",
    departureDate: "Aug 28, 2026",
    returnDate: "Aug 31, 2026",
    passengers: "2 pax",
    aircraftPreference: "Light Jet",
    tripNotes: "Pet traveling onboard (small dog).",
    internalNotes: "Flexible on flight times.",
    estValue: "$18,000",
    activities: [
      {
        id: "LACT-7",
        title: "Quote emailed to client",
        timestamp: "Jul 29, 2026 · 16:20",
        author: "Ari",
      },
    ],
    followUpsList: [
      {
        id: "LFU-4",
        title: "Aug 18, 2026 · Email",
        subtitle: "Assigned to Ari",
        status: "Upcoming",
      },
    ],
  },
  {
    id: "LD-205",
    name: "Marcus Webb",
    company: "Webb Enterprises",
    email: "marcus.webb@webbent.com",
    phone: "+1 (713) 555-0132",
    source: "Direct",
    origin: "TEB",
    destination: "MIA",
    route: "NYC → Miami",
    interest: "Executive roadshow",
    priority: "High",
    broker: "Barry",
    brokerId: "AGT-101",
    nextFollowUp: "Aug 12, 2026",
    followUpTime: "09:00 AM",
    followUpMethod: "Call",
    status: "Proposal",
    createdDate: "Aug 9, 2026",
    departureAirport: "KTEB",
    destinationAirport: "KMIA",
    departureDate: "Aug 22, 2026",
    returnDate: "Aug 26, 2026",
    passengers: "5 pax",
    aircraftPreference: "Heavy Jet",
    tripNotes: "VIP catering requested.",
    internalNotes: "Referred by Jonathan Reed.",
    estValue: "$31,500",
    activities: [
      {
        id: "LACT-8",
        title: "Direct referral received",
        timestamp: "Aug 9, 2026 · 07:30",
        author: "Barry",
      },
    ],
    followUpsList: [
      {
        id: "LFU-5",
        title: "Aug 12, 2026 · Call",
        subtitle: "Assigned to Barry",
        status: "Upcoming",
      },
    ],
  },
  {
    id: "LD-206",
    name: "James Holloway",
    company: "Holloway LLC",
    email: "james.holloway@hollowayllc.com",
    phone: "+1 (404) 555-0199",
    source: "Referral",
    origin: "TEB",
    destination: "MIA",
    route: "NYC → Miami",
    interest: "Annual investor summit",
    priority: "High",
    broker: "Barry",
    brokerId: "AGT-101",
    nextFollowUp: "Aug 10, 2026",
    followUpTime: "03:00 PM",
    followUpMethod: "Call",
    status: "Won",
    createdDate: "Jun 28, 2026",
    departureAirport: "KTEB",
    destinationAirport: "KMIA",
    departureDate: "Jul 15, 2026",
    returnDate: "Jul 20, 2026",
    passengers: "10 pax",
    aircraftPreference: "Ultra Long Range",
    tripNotes: "Booked and completed successfully.",
    internalNotes: "Ready to convert to long-term charter contract.",
    estValue: "$48,000",
    activities: [
      {
        id: "LACT-9",
        title: "Lead converted - Trip TJ-1045 confirmed",
        timestamp: "Jul 1, 2026 · 15:00",
        author: "Barry",
      },
    ],
    followUpsList: [],
  },
  {
    id: "LD-207",
    name: "Victoria Price",
    company: "Price Capital",
    email: "victoria.price@pricecap.com",
    phone: "+1 (212) 555-0190",
    source: "Website",
    origin: "HPN",
    destination: "PBI",
    route: "Westchester → Palm Beach",
    interest: "Westchester to Palm Beach round trip",
    priority: "Medium",
    broker: "Mark",
    brokerId: "AGT-102",
    nextFollowUp: "Aug 15, 2026",
    followUpTime: "11:00 AM",
    followUpMethod: "Email",
    status: "New",
    createdDate: "Aug 10, 2026",
    departureAirport: "KHPN",
    destinationAirport: "KPBI",
    departureDate: "Aug 24, 2026",
    returnDate: "Aug 29, 2026",
    passengers: "3 pax",
    aircraftPreference: "Midsize Jet",
    tripNotes: "Prefers Citation XLS or Hawker 800XP.",
    internalNotes: "First-time private charter buyer.",
    estValue: "$24,000",
    activities: [
      {
        id: "LACT-10",
        title: "New lead captured via website",
        timestamp: "Aug 10, 2026 · 08:45",
        author: "System",
      },
    ],
    followUpsList: [
      {
        id: "LFU-6",
        title: "Aug 15, 2026 · Email",
        subtitle: "Assigned to Mark",
        status: "Upcoming",
      },
    ],
  },
  {
    id: "LD-208",
    name: "Arthur Hayes",
    company: "Hayes Tech",
    email: "a.hayes@hayestech.io",
    phone: "+1 (415) 555-0122",
    source: "Direct",
    origin: "SFO",
    destination: "LAS",
    route: "San Francisco → Las Vegas",
    interest: "Tech conference group charter",
    priority: "High",
    broker: "Benny",
    brokerId: "AGT-103",
    nextFollowUp: "Aug 11, 2026",
    followUpTime: "01:00 PM",
    followUpMethod: "Call",
    status: "Quoted",
    createdDate: "Aug 4, 2026",
    departureAirport: "KSFO",
    destinationAirport: "KLAS",
    departureDate: "Sep 2, 2026",
    returnDate: "Sep 5, 2026",
    passengers: "7 pax",
    aircraftPreference: "Super Midsize",
    tripNotes: "Late night departure preference.",
    internalNotes: "Sent Challenger 350 quote.",
    estValue: "$29,000",
    activities: [
      {
        id: "LACT-11",
        title: "Formal quote #Q-408 sent",
        timestamp: "Aug 6, 2026 · 14:15",
        author: "Benny",
      },
    ],
    followUpsList: [
      {
        id: "LFU-7",
        title: "Aug 11, 2026 · Call",
        subtitle: "Assigned to Benny",
        status: "Upcoming",
      },
    ],
  },
  {
    id: "LD-209",
    name: "Elena Rostova",
    company: "Rostova Intl",
    email: "elena@rostovaintl.com",
    phone: "+1 (305) 555-0167",
    source: "Referral",
    origin: "MIA",
    destination: "NAS",
    route: "Miami → Nassau",
    interest: "Island charter for family",
    priority: "Medium",
    broker: "Ari",
    brokerId: "AGT-104",
    nextFollowUp: "Aug 16, 2026",
    followUpTime: "10:30 AM",
    followUpMethod: "WhatsApp",
    status: "Contacted",
    createdDate: "Aug 6, 2026",
    departureAirport: "KMIA",
    destinationAirport: "MYNN",
    departureDate: "Aug 29, 2026",
    returnDate: "Sep 3, 2026",
    passengers: "5 pax",
    aircraftPreference: "Light Jet / Turboprop",
    tripNotes: "Passports and customs clearing needed.",
    internalNotes: "Prefers messaging via WhatsApp.",
    estValue: "$15,500",
    activities: [
      {
        id: "LACT-12",
        title: "WhatsApp message initiated",
        timestamp: "Aug 6, 2026 · 11:45",
        author: "Ari",
      },
    ],
    followUpsList: [
      {
        id: "LFU-8",
        title: "Aug 16, 2026 · WhatsApp",
        subtitle: "Assigned to Ari",
        status: "Upcoming",
      },
    ],
  },
  {
    id: "LD-210",
    name: "David Kim",
    company: "Kim Global",
    email: "dkim@kimglobal.com",
    phone: "+1 (206) 555-0188",
    source: "Email",
    origin: "SEA",
    destination: "LAX",
    route: "Seattle → Los Angeles",
    interest: "Corporate travel recurring",
    priority: "Low",
    broker: "Barry",
    brokerId: "AGT-101",
    nextFollowUp: "Aug 20, 2026",
    followUpTime: "03:30 PM",
    followUpMethod: "Email",
    status: "New",
    createdDate: "Aug 9, 2026",
    departureAirport: "KBFI",
    destinationAirport: "KVNY",
    departureDate: "Sep 10, 2026",
    returnDate: "Sep 12, 2026",
    passengers: "2 pax",
    aircraftPreference: "Light Jet",
    tripNotes: "Flexible departure times.",
    internalNotes: "Reviewing multiple jet cards.",
    estValue: "$16,000",
    activities: [
      {
        id: "LACT-13",
        title: "Inbound email received",
        timestamp: "Aug 9, 2026 · 16:00",
        author: "System",
      },
    ],
    followUpsList: [
      {
        id: "LFU-9",
        title: "Aug 20, 2026 · Email",
        subtitle: "Assigned to Barry",
        status: "Upcoming",
      },
    ],
  },
  {
    id: "LD-211",
    name: "Rachel Adams",
    company: "Adams Partners",
    email: "radams@adamspartners.com",
    phone: "+1 (617) 555-0143",
    source: "Website",
    origin: "BOS",
    destination: "TEB",
    route: "Boston → Teterboro",
    interest: "Weekly shuttle charter",
    priority: "High",
    broker: "Mark",
    brokerId: "AGT-102",
    nextFollowUp: "Aug 13, 2026",
    followUpTime: "09:30 AM",
    followUpMethod: "Call",
    status: "Qualified",
    createdDate: "Aug 7, 2026",
    departureAirport: "KBED",
    destinationAirport: "KTEB",
    departureDate: "Aug 25, 2026",
    returnDate: "Aug 25, 2026",
    passengers: "4 pax",
    aircraftPreference: "Turboprop / Light Jet",
    tripNotes: "Same-day return charter.",
    internalNotes: "High potential for 20+ flights/year.",
    estValue: "$12,000",
    activities: [
      {
        id: "LACT-14",
        title: "Qualification interview completed",
        timestamp: "Aug 8, 2026 · 14:00",
        author: "Mark",
      },
    ],
    followUpsList: [
      {
        id: "LFU-10",
        title: "Aug 13, 2026 · Call",
        subtitle: "Assigned to Mark",
        status: "Upcoming",
      },
    ],
  },
  {
    id: "LD-212",
    name: "Liam O'Connor",
    company: "O'Connor Corp",
    email: "liam@oconnorcorp.com",
    phone: "+1 (312) 555-0155",
    source: "Direct",
    origin: "MDW",
    destination: "MIA",
    route: "Chicago → Miami",
    interest: "Winter seasonal flights",
    priority: "Medium",
    broker: "Benny",
    brokerId: "AGT-103",
    nextFollowUp: "Aug 17, 2026",
    followUpTime: "12:00 PM",
    followUpMethod: "Call",
    status: "Proposal",
    createdDate: "Aug 2, 2026",
    departureAirport: "KMDW",
    destinationAirport: "KMIA",
    departureDate: "Sep 15, 2026",
    returnDate: "Sep 22, 2026",
    passengers: "6 pax",
    aircraftPreference: "Heavy Jet",
    tripNotes: "Special catering and ground transport in Chicago.",
    internalNotes: "Awaiting final schedule confirmation.",
    estValue: "$38,000",
    activities: [
      {
        id: "LACT-15",
        title: "Proposal rev 2 sent",
        timestamp: "Aug 4, 2026 · 10:15",
        author: "Benny",
      },
    ],
    followUpsList: [
      {
        id: "LFU-11",
        title: "Aug 17, 2026 · Call",
        subtitle: "Assigned to Benny",
        status: "Upcoming",
      },
    ],
  },
];

export const agentAssignedLeads = leadsData.filter((l) => l.brokerId === "AGT-101");

export const agentAssociatedTrips = [
  {
    id: "TJ-1049",
    agentId: "AGT-101",
    client: "Michael Anderson",
    origin: "TEB",
    destination: "MIA",
    dateTime: "Aug 14, 2026 · 09:30",
    status: "In Progress",
  },
  {
    id: "TJ-1047",
    agentId: "AGT-101",
    client: "Robert Walsh",
    origin: "HPN",
    destination: "PBI",
    dateTime: "Aug 16, 2026 · 08:00",
    status: "Scheduled",
  },
  {
    id: "TJ-1052",
    agentId: "AGT-101",
    client: "James Kellner",
    origin: "VNY",
    destination: "LAS",
    dateTime: "Aug 20, 2026 · 10:00",
    status: "Scheduled",
  },
  {
    id: "TJ-1053",
    agentId: "AGT-101",
    client: "Elena Voss",
    origin: "MIA",
    destination: "NAS",
    dateTime: "Aug 22, 2026 · 09:00",
    status: "Draft",
  },
  {
    id: "TJ-1045",
    agentId: "AGT-101",
    client: "Mike Anderson",
    origin: "TEB",
    destination: "MIA",
    dateTime: "Aug 12, 2026 · 14:00",
    status: "Confirmed",
  },
];

export const agentRecentActivities = [
  {
    id: "ACT-1",
    agentId: "AGT-101",
    title: "Lead created from direct inquiry",
    lead: "Jonathan Reed",
    timestamp: "Aug 8, 2026 · 10:15",
  },
  {
    id: "ACT-2",
    agentId: "AGT-101",
    title: "Welcome email sent to jonathan.reed@reedcapital.com",
    lead: "Jonathan Reed",
    timestamp: "Aug 8, 2026 · 11:00",
  },
  {
    id: "ACT-3",
    agentId: "AGT-101",
    title: "Lead created — referral from Jonathan Reed",
    lead: "Marcus Webb",
    timestamp: "Aug 9, 2026 · 07:30",
  },
  {
    id: "ACT-4",
    agentId: "AGT-101",
    title: "Follow-up email sent with company overview",
    lead: "Emily Carter",
    timestamp: "Aug 7, 2026 · 09:30",
  },
  {
    id: "ACT-5",
    agentId: "AGT-101",
    title: "Qualification call — budget and dates confirmed",
    lead: "Emily Carter",
    timestamp: "Aug 8, 2026 · 11:00",
  },
];
