export const operatorStatusOptions = ["All", "Active", "Preferred", "Inactive"];

export const operatorsStats = [
  { label: "TOTAL OPERATORS", value: 4 },
  { label: "ACTIVE", value: 3, highlight: "success" },
  { label: "PREFERRED", value: 2, highlight: "purple" },
  { label: "TOTAL FLEET", value: 18 },
];

export const operatorsData = [
  {
    id: "OP-1001",
    name: "FlexJet",
    status: "Preferred",
    homeBase: "Cleveland, OH",
    primaryContact: "James Miller",
    email: "jmiller@flexjet.com",
    phone: "+1 (212) 555-0184",
    website: "www.flexjet.com",
    aircraftTypes: ["Global 7500", "Challenger 350"],
    reliability: 4.8,
    safety: "ARG/US Platinum",
    responseSpeed: "< 15 min",
    totalTrips: 24,
    totalPaid: "$0",
    sourcingNotes: "Preferred long-range partner with direct dispatch line. High reliability on transcontinental routes.",
    serviceRoutes: ["KTEB ↔ KMIA", "KJFK ↔ EGLL", "KLAX ↔ KLAS"],
    cancellationPolicy: "Full refund up to 72 hours prior to departure. 50% fee within 48-72h. 100% fee within 24h.",
    paymentTerms: "Net 30",
    fleet: [
      {
        id: "FL-1",
        model: "Global 7500",
        type: "Ultra Long Range",
        tail: "N785EX",
        capacity: "16 pax",
        rangeNm: "7,700",
        year: "2021",
        trips: 18,
        status: "Available",
      },
      {
        id: "FL-2",
        model: "Challenger 350",
        type: "Super Midsize",
        tail: "N680EX",
        capacity: "9 pax",
        rangeNm: "3,500",
        year: "2020",
        trips: 22,
        status: "Available",
      },
      {
        id: "FL-3",
        model: "Praetor 600",
        type: "Super Midsize",
        tail: "N420EX",
        capacity: "10 pax",
        rangeNm: "4,018",
        year: "2022",
        trips: 14,
        status: "Maintenance",
      },
    ],
    tripHistory: [
      {
        tripId: "TJ-1051",
        route: "KTEB → KMIA",
        aircraft: "Global 7500",
        departure: "Aug 20, 2026",
        client: "Sarah Chen",
        price: "$51,000",
        status: "Confirmed",
        broker: "Barry Wilson",
      },
      {
        tripId: "TJ-1052",
        route: "KJFK → EGLL",
        aircraft: "Global 7500",
        departure: "Aug 22, 2026",
        client: "David Park",
        price: "$62,000",
        status: "Completed",
        broker: "Ari Wohl",
      },
      {
        tripId: "TJ-1043",
        route: "KLAX → KLAS",
        aircraft: "Challenger 350",
        departure: "Aug 10, 2026",
        client: "Mike Anderson",
        price: "$14,800",
        status: "Completed",
        broker: "Mark Vance",
      },
      {
        tripId: "TJ-1046",
        route: "KVNY → KSFO",
        aircraft: "Challenger 350",
        departure: "Aug 16, 2026",
        client: "Hope Sterling",
        price: "$6,400",
        status: "Confirmed",
        broker: "Barry Wilson",
      },
      {
        tripId: "TJ-1026",
        route: "KTEB → KPBI",
        aircraft: "Challenger 350",
        departure: "Aug 9, 2026",
        client: "Sarah Chen",
        price: "$12,200",
        status: "Completed",
        broker: "Barry Wilson",
      },
    ],
    payments: [
      {
        tripId: "TJ-1051",
        amount: "$51,000",
        paid: "$0",
        balance: "$51,000",
        due: "Aug 20, 2026",
        status: "Pending",
        broker: "Mark Vance",
      },
      {
        tripId: "TJ-1052",
        amount: "$62,000",
        paid: "$62,000",
        balance: "$0",
        due: "Aug 22, 2026",
        status: "Paid",
        broker: "Barry Wilson",
      },
      {
        tripId: "TJ-1043",
        amount: "$14,800",
        paid: "$0",
        balance: "$14,800",
        due: "Aug 10, 2026",
        status: "Due",
        broker: "Mark Vance",
      },
      {
        tripId: "TJ-1046",
        amount: "$6,400",
        paid: "$0",
        balance: "$6,400",
        due: "Aug 16, 2026",
        status: "Pending",
        broker: "Barry Wilson",
      },
      {
        tripId: "TJ-1026",
        amount: "$12,200",
        paid: "$12,200",
        balance: "$0",
        due: "Aug 9, 2026",
        status: "Paid",
        broker: "Barry Wilson",
      },
    ],
  },
  {
    id: "OP-1002",
    name: "VistaJet",
    status: "Active",
    homeBase: "Luton, UK",
    primaryContact: "Sarah Blake",
    email: "sblake@vistajet.com",
    phone: "+44 20 7946 0912",
    website: "www.vistajet.com",
    aircraftTypes: ["Global 7500", "Global 6000"],
    reliability: 4.7,
    safety: "Wyvern Wingman",
    responseSpeed: "< 20 min",
    totalTrips: 18,
    totalPaid: "$114,000",
    sourcingNotes: "Excellent global coverage with distinctive silver and red stripe fleet.",
    serviceRoutes: ["EGLL ↔ KJFK", "EGGW ↔ OMDB", "LFMN ↔ KTEB"],
    cancellationPolicy: "Standard international charter terms. 10% non-refundable deposit.",
    paymentTerms: "Net 15",
    fleet: [
      {
        id: "FL-4",
        model: "Global 7500",
        type: "Ultra Long Range",
        tail: "9H-VIZ",
        capacity: "14 pax",
        rangeNm: "7,700",
        year: "2021",
        trips: 18,
        status: "Available",
      },
      {
        id: "FL-5",
        model: "Global 6000",
        type: "Ultra Long Range",
        tail: "9H-VJA",
        capacity: "14 pax",
        rangeNm: "6,000",
        year: "2018",
        trips: 22,
        status: "Maintenance",
      },
    ],
    tripHistory: [
      {
        tripId: "TJ-1039",
        route: "EGLL → KJFK",
        aircraft: "Global 7500",
        departure: "Aug 02, 2026",
        client: "David Park",
        price: "$78,000",
        status: "Completed",
        broker: "Ari Wohl",
      },
      {
        tripId: "TJ-1048",
        route: "EGGW → OMDB",
        aircraft: "Global 6000",
        departure: "Aug 14, 2026",
        client: "Hope Sterling",
        price: "$65,000",
        status: "Confirmed",
        broker: "Barry Wilson",
      },
    ],
    payments: [
      {
        tripId: "TJ-1039",
        amount: "$78,000",
        paid: "$78,000",
        balance: "$0",
        due: "Aug 02, 2026",
        status: "Paid",
        broker: "Ari Wohl",
      },
      {
        tripId: "TJ-1048",
        amount: "$65,000",
        paid: "$36,000",
        balance: "$29,000",
        due: "Aug 14, 2026",
        status: "Due",
        broker: "Barry Wilson",
      },
    ],
  },
  {
    id: "OP-1003",
    name: "ExecuJet",
    status: "Active",
    homeBase: "Zurich, CH",
    primaryContact: "Mark Hughes",
    email: "mhughes@execujet.com",
    phone: "+41 44 804 1616",
    website: "www.execujet.com",
    aircraftTypes: ["Gulfstream G550", "Falcon 7X"],
    reliability: 4.6,
    safety: "IS-BAO Stage 3",
    responseSpeed: "< 30 min",
    totalTrips: 22,
    totalPaid: "$68,500",
    sourcingNotes: "Premier European charter operator with heavy jet capabilities.",
    serviceRoutes: ["LSZH ↔ LFMN", "LSGG ↔ EGLL"],
    cancellationPolicy: "Standard European business aviation contract.",
    paymentTerms: "Due upon receipt",
    fleet: [
      {
        id: "FL-6",
        model: "Gulfstream G550",
        type: "Heavy Jet",
        tail: "HB-JEX",
        capacity: "14 pax",
        rangeNm: "6,750",
        year: "2019",
        trips: 24,
        status: "Available",
      },
      {
        id: "FL-7",
        model: "Falcon 7X",
        type: "Heavy Jet",
        tail: "HB-FOX",
        capacity: "12 pax",
        rangeNm: "5,950",
        year: "2020",
        trips: 16,
        status: "Available",
      },
    ],
    tripHistory: [
      {
        tripId: "TJ-1033",
        route: "LSZH → LFMN",
        aircraft: "Falcon 7X",
        departure: "Jul 28, 2026",
        client: "Sarah Chen",
        price: "$28,500",
        status: "Completed",
        broker: "Barry Wilson",
      },
    ],
    payments: [
      {
        tripId: "TJ-1033",
        amount: "$28,500",
        paid: "$28,500",
        balance: "$0",
        due: "Jul 28, 2026",
        status: "Paid",
        broker: "Barry Wilson",
      },
    ],
  },
  {
    id: "OP-1004",
    name: "NetJets",
    status: "Preferred",
    homeBase: "Columbus, OH",
    primaryContact: "Jennifer Vance",
    email: "jvance@netjets.com",
    phone: "+1 (877) 356-5825",
    website: "www.netjets.com",
    aircraftTypes: ["Citation Latitude", "Challenger 650", "Global 6000"],
    reliability: 4.9,
    safety: "ARG/US Platinum",
    responseSpeed: "< 10 min",
    totalTrips: 35,
    totalPaid: "$240,000",
    sourcingNotes: "Largest private jet operator globally. Instant guaranteed availability.",
    serviceRoutes: ["KCMH ↔ KTEB", "KTEB ↔ KPBI", "KLAX ↔ KSFO"],
    cancellationPolicy: "NetJets broker agreement terms with 48-hour cancellation grace period.",
    paymentTerms: "Net 30",
    fleet: [
      {
        id: "FL-8",
        model: "Citation Latitude",
        type: "Midsize",
        tail: "N510QS",
        capacity: "8 pax",
        rangeNm: "2,700",
        year: "2022",
        trips: 30,
        status: "Available",
      },
      {
        id: "FL-9",
        model: "Challenger 650",
        type: "Heavy Jet",
        tail: "N650QS",
        capacity: "12 pax",
        rangeNm: "4,000",
        year: "2021",
        trips: 28,
        status: "Available",
      },
    ],
    tripHistory: [],
    payments: [],
  },
];
