export const quotesKPIStats = [
  { label: "TOTAL QUOTES", value: "4", tone: "foreground" },
  { label: "AWAITING RESPONSE", value: "1", tone: "warning" },
  { label: "APPROVED", value: "1", tone: "success" },
  { label: "TOTAL VALUE", value: "$281,113", tone: "foreground" },
];

export const quoteStatusOptions = [
  "All Status",
  "Draft",
  "Sent",
  "Viewed",
  "Approved",
  "Rejected",
  "Expired",
];

export const quoteBrokerOptions = [
  "All Brokers",
  "Barry Wilson",
  "Mark Evans",
  "Benny Carter",
  "Ari Wohl",
];

export const quoteClientsOptions = [
  { name: "Jonathan Reed", company: "Reed Capital", tier: "VIP" },
  { name: "Hope Sterling", company: "Sterling Group", tier: "VIP" },
  { name: "Emily Carter", company: "Carter Air", tier: "Standard" },
  { name: "Robert Walsh", company: "Walsh Enterprises", tier: "VIP" },
  { name: "David Chen", company: "Apex Holdings", tier: "Standard" },
  { name: "Sarah Jenkins", company: "Jenkins Global", tier: "VIP" },
];

export const quoteAircraftOptions = [
  "Gulfstream G550",
  "Global 7500",
  "Citation Latitude",
  "Citation XLS",
  "Challenger 605",
  "Challenger 350",
  "Falcon 7X",
];

export const quotesData = [
  {
    id: "Q-2026-042",
    client: "Jonathan Reed",
    clientTier: "VIP",
    company: "Reed Capital",
    broker: "Barry",
    brokerFullName: "Barry Wilson",
    origin: "KTEB",
    destination: "KPBI",
    route: "KTEB → KPBI",
    date: "Aug 15",
    departureDate: "2026-08-15",
    returnDate: "2026-08-18",
    departureAirport: "KTEB",
    destinationAirport: "KPBI",
    aircraft: "Gulfstream G550",
    operator: "ExecuJet",
    basePrice: 79500,
    basePriceFormatted: "$79,500",
    fetAmount: 5963,
    fetFormatted: "$5,963",
    fetEnabled: true,
    totalPrice: 85463,
    totalPriceFormatted: "$85,463",
    operatorCost: 65000,
    operatorCostFormatted: "$65,000",
    grossProfit: 20463,
    grossProfitFormatted: "$20,463",
    marginPercentage: "23.9%",
    version: "V3",
    status: "Sent",
    sentDate: "Aug 9",
    expiryDate: "Aug 12",
    lineItems: [
      { label: "Base Charter Price", amount: "$79,500", type: "currency" },
      { label: "Federal Excise Tax (7.5%)", amount: "$5,963", type: "currency" },
      { label: "Catering (Seafood Premium)", amount: "Included", type: "text" },
      { label: "Ground Transportation", amount: "Included", type: "text" },
    ],
    versions: [
      {
        version: "V3",
        amount: "$85,463",
        note: "Adjusted FET and catering",
        date: "Aug 10",
        isCurrent: true,
      },
      {
        version: "V2",
        amount: "$82,500",
        note: "Added return leg",
        date: "Aug 10",
        isCurrent: false,
      },
      {
        version: "V1",
        amount: "$78,000",
        note: "Initial quote...",
        date: "Aug 10",
        isCurrent: false,
      },
    ],
    notes:
      "Hope prefers morning departures. Always book catering — seafood preferred. Send itinerary PDF 48 hours prior. Strongly prefers ExecuJet as operator. Birthday: March 14.",
  },
  {
    id: "Q-2026-039",
    client: "Hope Sterling",
    clientTier: "VIP",
    company: "Sterling Group",
    broker: "Mark",
    brokerFullName: "Mark Evans",
    origin: "KTEB",
    destination: "KMIA",
    route: "KTEB → KMIA",
    date: "Sep 3",
    departureDate: "2026-09-03",
    returnDate: "2026-09-06",
    departureAirport: "KTEB",
    destinationAirport: "KMIA",
    aircraft: "Global 7500",
    operator: "VistaJet",
    basePrice: 118500,
    basePriceFormatted: "$118,500",
    fetAmount: 8350,
    fetFormatted: "$8,350",
    fetEnabled: true,
    totalPrice: 126850,
    totalPriceFormatted: "$126,850",
    operatorCost: 98000,
    operatorCostFormatted: "$98,000",
    grossProfit: 28850,
    grossProfitFormatted: "$28,850",
    marginPercentage: "22.7%",
    version: "V2",
    status: "Approved",
    sentDate: "Aug 8",
    expiryDate: "Aug 15",
    lineItems: [
      { label: "Base Charter Price", amount: "$118,500", type: "currency" },
      { label: "Federal Excise Tax (7.5%)", amount: "$8,350", type: "currency" },
      { label: "VIP Catering Package", amount: "Included", type: "text" },
      { label: "Ramp VIP Fast-Track", amount: "Included", type: "text" },
    ],
    versions: [
      {
        version: "V2",
        amount: "$126,850",
        note: "Updated to Global 7500",
        date: "Aug 8",
        isCurrent: true,
      },
      {
        version: "V1",
        amount: "$115,000",
        note: "Initial proposal with Gulfstream G650",
        date: "Aug 5",
        isCurrent: false,
      },
    ],
    notes:
      "Client confirmed flight itinerary. Ground transportation requested at KMIA with executive SUV.",
  },
  {
    id: "Q-2026-040",
    client: "Emily Carter",
    clientTier: "Standard",
    company: "Carter Air",
    broker: "Barry",
    brokerFullName: "Barry Wilson",
    origin: "KMIA",
    destination: "EGLL",
    route: "KMIA → EGLL",
    date: "Aug 16",
    departureDate: "2026-08-16",
    returnDate: "2026-08-22",
    departureAirport: "KMIA",
    destinationAirport: "EGLL",
    aircraft: "Citation Latitude",
    operator: "NetJets Europe",
    basePrice: 28000,
    basePriceFormatted: "$28,000",
    fetAmount: 2100,
    fetFormatted: "$2,100",
    fetEnabled: true,
    totalPrice: 30100,
    totalPriceFormatted: "$30,100",
    operatorCost: 22500,
    operatorCostFormatted: "$22,500",
    grossProfit: 7600,
    grossProfitFormatted: "$7,600",
    marginPercentage: "25.2%",
    version: "V1",
    status: "Draft",
    sentDate: "Aug 10",
    expiryDate: "Aug 16",
    lineItems: [
      { label: "Base Charter Price", amount: "$28,000", type: "currency" },
      { label: "Federal Excise Tax (7.5%)", amount: "$2,100", type: "currency" },
      { label: "Standard Catering", amount: "Included", type: "text" },
    ],
    versions: [
      {
        version: "V1",
        amount: "$30,100",
        note: "Initial Draft",
        date: "Aug 10",
        isCurrent: true,
      },
    ],
    notes: "Awaiting final confirmation on passenger count before issuing quote to client.",
  },
  {
    id: "Q-2026-043",
    client: "Robert Walsh",
    clientTier: "VIP",
    company: "Walsh Enterprises",
    broker: "Mark",
    brokerFullName: "Mark Evans",
    origin: "KTEB",
    destination: "KPBI",
    route: "KTEB → KPBI",
    date: "Aug 14",
    departureDate: "2026-08-14",
    returnDate: "2026-08-16",
    departureAirport: "KTEB",
    destinationAirport: "KPBI",
    aircraft: "Citation XLS",
    operator: "Clay Lacy",
    basePrice: 36000,
    basePriceFormatted: "$36,000",
    fetAmount: 2700,
    fetFormatted: "$2,700",
    fetEnabled: true,
    totalPrice: 38700,
    totalPriceFormatted: "$38,700",
    operatorCost: 29000,
    operatorCostFormatted: "$29,000",
    grossProfit: 9700,
    grossProfitFormatted: "$9,700",
    marginPercentage: "25.1%",
    version: "V1",
    status: "Expired",
    sentDate: "Aug 4",
    expiryDate: "Aug 8",
    lineItems: [
      { label: "Base Charter Price", amount: "$36,000", type: "currency" },
      { label: "Federal Excise Tax (7.5%)", amount: "$2,700", type: "currency" },
      { label: "Standard Catering", amount: "Included", type: "text" },
    ],
    versions: [
      {
        version: "V1",
        amount: "$38,700",
        note: "Initial Quote",
        date: "Aug 4",
        isCurrent: true,
      },
    ],
    notes: "Quote expired due to lack of client confirmation within 72 hours window.",
  },
  {
    id: "Q-2026-044",
    client: "Hope Sterling",
    clientTier: "VIP",
    company: "Sterling Group",
    broker: "Barry",
    brokerFullName: "Barry Wilson",
    origin: "KTEB",
    destination: "KPBI",
    route: "KTEB → KPBI",
    date: "Aug 12",
    departureDate: "2026-08-12",
    returnDate: "2026-08-15",
    departureAirport: "KTEB",
    destinationAirport: "KPBI",
    aircraft: "Global 7500",
    operator: "ExecuJet",
    basePrice: 36000,
    basePriceFormatted: "$36,000",
    fetAmount: 2700,
    fetFormatted: "$2,700",
    fetEnabled: true,
    totalPrice: 38700,
    totalPriceFormatted: "$38,700",
    operatorCost: 28500,
    operatorCostFormatted: "$28,500",
    grossProfit: 10200,
    grossProfitFormatted: "$10,200",
    marginPercentage: "26.4%",
    version: "V1",
    status: "Draft",
    sentDate: "Aug 11",
    expiryDate: "Aug 14",
    lineItems: [
      { label: "Base Charter Price", amount: "$36,000", type: "currency" },
      { label: "Federal Excise Tax (7.5%)", amount: "$2,700", type: "currency" },
      { label: "Executive Catering", amount: "Included", type: "text" },
    ],
    versions: [
      {
        version: "V1",
        amount: "$38,700",
        note: "Draft created by Barry",
        date: "Aug 11",
        isCurrent: true,
      },
    ],
    notes: "Draft review with senior management before sending to Hope.",
  },
  {
    id: "Q-2026-045",
    client: "David Chen",
    clientTier: "Standard",
    company: "Apex Holdings",
    broker: "Ari",
    brokerFullName: "Ari Wohl",
    origin: "KLAX",
    destination: "KLAS",
    route: "KLAX → KLAS",
    date: "Aug 20",
    departureDate: "2026-08-20",
    returnDate: "2026-08-22",
    departureAirport: "KLAX",
    destinationAirport: "KLAS",
    aircraft: "Challenger 350",
    operator: "XOJET",
    basePrice: 22000,
    basePriceFormatted: "$22,000",
    fetAmount: 1650,
    fetFormatted: "$1,650",
    fetEnabled: true,
    totalPrice: 23650,
    totalPriceFormatted: "$23,650",
    operatorCost: 17500,
    operatorCostFormatted: "$17,500",
    grossProfit: 6150,
    grossProfitFormatted: "$6,150",
    marginPercentage: "26.0%",
    version: "V1",
    status: "Viewed",
    sentDate: "Aug 11",
    expiryDate: "Aug 18",
    lineItems: [
      { label: "Base Charter Price", amount: "$22,000", type: "currency" },
      { label: "Federal Excise Tax (7.5%)", amount: "$1,650", type: "currency" },
      { label: "Beverage Service", amount: "Included", type: "text" },
    ],
    versions: [
      {
        version: "V1",
        amount: "$23,650",
        note: "Initial Quote",
        date: "Aug 11",
        isCurrent: true,
      },
    ],
    notes: "Client viewed proposal online, follow-up scheduled for tomorrow.",
  },
];

