export const scheduleStats = [
  { label: "Flights Today", value: "4", tone: "foreground" },
  { label: "Departures", value: "3", tone: "warning" },
  { label: "Arrivals", value: "3", tone: "info" },
  { label: "In Flight", value: "1", tone: "destructive" },
  { label: "Upcoming", value: "18", tone: "foreground" },
  { label: "Completed", value: "2", tone: "success" },
];

export const REFERENCE_TODAY = "2026-08-10";

export const scheduleStatusOptions = ["All", "Confirmed", "Booked", "Sourcing", "In Flight", "Completed"];
export const scheduleBrokerOptions = ["All", "Internal (Direct)", "Skyline Partners", "Elite Air Brokers"];
export const scheduleOperatorOptions = ["All", "VistaJet", "NetJets", "Flexjet", "Wheels Up"];
export const scheduleAircraftOptions = ["All", "Global 6000", "Citation XLS", "Phenom 300", "Gulfstream G550"];
export const scheduleTripTypeOptions = ["All", "One Way", "Round Trip"];

export const scheduleEvents = [
  {
    id: "TJ-1045",
    tripId: "TRP-88190-A",
    date: "2026-08-10",
    time: "08:00",
    arrivalTime: "10:12",
    duration: "2h 12m",
    client: "Sarah Chen",
    from: "KJFK",
    to: "KMIA",
    aircraft: "Global 6000",
    tailNumber: "N600GJ",
    operator: "VistaJet",
    broker: "Internal (Direct)",
    tripType: "One Way",
    status: "Confirmed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1046",
    tripId: "TRP-88192-A",
    date: "2026-08-10",
    time: "12:00",
    arrivalTime: "14:35",
    duration: "2h 35m",
    client: "David Park",
    from: "KTEB",
    to: "KPBI",
    aircraft: "Citation XLS",
    tailNumber: "N235CX",
    operator: "NetJets",
    broker: "Skyline Partners",
    tripType: "Round Trip",
    status: "Booked",
    paymentStatus: "Pending",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1047",
    tripId: "TRP-88198-A",
    date: "2026-08-10",
    time: "16:00",
    arrivalTime: "17:20",
    duration: "1h 20m",
    client: "James Kellner",
    from: "KLAS",
    to: "KTEB",
    aircraft: "Global 6000",
    tailNumber: "N600GJ",
    operator: "VistaJet",
    broker: "Internal (Direct)",
    tripType: "One Way",
    status: "In Flight",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1049",
    tripId: "TRP-88201-A",
    date: "2026-08-10",
    time: "09:00",
    arrivalTime: "11:30",
    duration: "2h 30m",
    client: "Hope Sterling",
    from: "KMIA",
    to: "KTEB",
    aircraft: "Phenom 300",
    tailNumber: "N300PH",
    operator: "Flexjet",
    broker: "Elite Air Brokers",
    tripType: "One Way",
    status: "Confirmed",
    paymentStatus: "Cleared",
    fetApplied: "No",
  },
  {
    id: "TJ-1050",
    tripId: "TRP-88204-A",
    date: "2026-08-11",
    time: "09:15",
    arrivalTime: "11:45",
    duration: "2h 30m",
    client: "Robert Walsh",
    from: "KTEB",
    to: "KPBI",
    aircraft: "Citation XLS",
    tailNumber: "N235CX",
    operator: "NetJets",
    broker: "Skyline Partners",
    tripType: "One Way",
    status: "Booked",
    paymentStatus: "Pending",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1051",
    tripId: "TRP-88206-A",
    date: "2026-08-11",
    time: "13:00",
    arrivalTime: "20:40",
    duration: "7h 40m",
    client: "Emily Carter",
    from: "KMIA",
    to: "EGLL",
    aircraft: "Global 6000",
    tailNumber: "N600GJ",
    operator: "VistaJet",
    broker: "Internal (Direct)",
    tripType: "Round Trip",
    status: "Confirmed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1052",
    tripId: "TRP-88210-A",
    date: "2026-08-12",
    time: "08:30",
    arrivalTime: "10:05",
    duration: "1h 35m",
    client: "Daniel Brooks",
    from: "KVNY",
    to: "KASE",
    aircraft: "Gulfstream G550",
    tailNumber: "N550GS",
    operator: "Wheels Up",
    broker: "Elite Air Brokers",
    tripType: "Round Trip",
    status: "Confirmed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1048",
    tripId: "TRP-88204-B",
    date: "2026-08-12",
    time: "10:00",
    arrivalTime: "13:05",
    duration: "3h 05m",
    client: "Hope Sterling",
    from: "KTEB",
    to: "KMIA",
    aircraft: "Gulfstream G550",
    tailNumber: "N550GS",
    operator: "VistaJet",
    broker: "Internal (Direct)",
    tripType: "Round Trip (Leg 1 of 2)",
    status: "Confirmed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1053",
    tripId: "TRP-88212-A",
    date: "2026-08-13",
    time: "16:15",
    arrivalTime: "18:50",
    duration: "2h 35m",
    client: "Alexis Reyes",
    from: "KLAS",
    to: "KTEB",
    aircraft: "Gulfstream G550",
    tailNumber: "N551GS",
    operator: "Wheels Up",
    broker: "Elite Air Brokers",
    tripType: "One Way",
    status: "Completed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-2403",
    tripId: "TRP-88214-A",
    date: "2026-08-14",
    time: "11:00",
    arrivalTime: "19:10",
    duration: "8h 10m",
    client: "Marcus Webb",
    from: "KMIA",
    to: "EGLL",
    aircraft: "Phenom 300",
    tailNumber: "N301PH",
    operator: "Flexjet",
    broker: "Internal (Direct)",
    tripType: "Round Trip",
    status: "Booked",
    paymentStatus: "Pending",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1055",
    tripId: "TRP-88218-A",
    date: "2026-08-15",
    time: "07:45",
    arrivalTime: "10:05",
    duration: "2h 20m",
    client: "Tyler Grant",
    from: "KMDW",
    to: "KFLL",
    aircraft: "Citation XLS",
    tailNumber: "N236CX",
    operator: "NetJets",
    broker: "Skyline Partners",
    tripType: "One Way",
    status: "Confirmed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1056",
    tripId: "TRP-88220-A",
    date: "2026-08-16",
    time: "15:30",
    arrivalTime: "18:05",
    duration: "2h 35m",
    client: "Chris Dalton",
    from: "KDAL",
    to: "KASE",
    aircraft: "Global 6000",
    tailNumber: "N601GJ",
    operator: "VistaJet",
    broker: "Internal (Direct)",
    tripType: "One Way",
    status: "Booked",
    paymentStatus: "Pending",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-2404",
    tripId: "TRP-88224-A",
    date: "2026-08-18",
    time: "09:20",
    arrivalTime: "10:55",
    duration: "1h 35m",
    client: "Priya Nadar",
    from: "KVNY",
    to: "KASE",
    aircraft: "Citation XLS",
    tailNumber: "N237CX",
    operator: "NetJets",
    broker: "Elite Air Brokers",
    tripType: "Round Trip",
    status: "Confirmed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1057",
    tripId: "TRP-88228-A",
    date: "2026-08-15",
    time: "12:00",
    arrivalTime: "14:15",
    duration: "2h 15m",
    client: "Natalie Brooks",
    from: "KJFK",
    to: "KMIA",
    aircraft: "Citation XLS",
    tailNumber: "N238CX",
    operator: "NetJets",
    broker: "Skyline Partners",
    tripType: "One Way",
    status: "Completed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-2405",
    tripId: "TRP-88232-A",
    date: "2026-08-24",
    time: "10:30",
    arrivalTime: "18:40",
    duration: "8h 10m",
    client: "Sophia Morgan",
    from: "KTEB",
    to: "LFPB",
    aircraft: "Global 6000",
    tailNumber: "N602GJ",
    operator: "VistaJet",
    broker: "Internal (Direct)",
    tripType: "Round Trip",
    status: "Sourcing",
    paymentStatus: "Pending",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-2407",
    tripId: "TRP-88236-A",
    date: "2026-08-27",
    time: "13:45",
    arrivalTime: "15:20",
    duration: "1h 35m",
    client: "David Chen",
    from: "KLAS",
    to: "KTEB",
    aircraft: "Phenom 300",
    tailNumber: "N302PH",
    operator: "Flexjet",
    broker: "Elite Air Brokers",
    tripType: "One Way",
    status: "In Flight",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1059",
    tripId: "TRP-88240-A",
    date: "2026-08-03",
    time: "10:30",
    arrivalTime: "12:50",
    duration: "2h 20m",
    client: "Jonathan Reed",
    from: "KTEB",
    to: "KPBI",
    aircraft: "Gulfstream G550",
    tailNumber: "N552GS",
    operator: "Wheels Up",
    broker: "Internal (Direct)",
    tripType: "One Way",
    status: "Completed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1061",
    tripId: "TRP-88244-A",
    date: "2026-07-14",
    time: "09:00",
    arrivalTime: "11:20",
    duration: "2h 20m",
    client: "Lauren Ashford",
    from: "KTEB",
    to: "KMIA",
    aircraft: "Citation XLS",
    tailNumber: "N239CX",
    operator: "NetJets",
    broker: "Skyline Partners",
    tripType: "One Way",
    status: "Completed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1062",
    tripId: "TRP-88248-A",
    date: "2026-09-05",
    time: "14:00",
    arrivalTime: "16:35",
    duration: "2h 35m",
    client: "Michael Ortiz",
    from: "KDAL",
    to: "KASE",
    aircraft: "Gulfstream G550",
    tailNumber: "N553GS",
    operator: "Wheels Up",
    broker: "Elite Air Brokers",
    tripType: "One Way",
    status: "Booked",
    paymentStatus: "Pending",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1063",
    tripId: "TRP-88252-A",
    date: "2026-10-21",
    time: "11:15",
    arrivalTime: "13:50",
    duration: "2h 35m",
    client: "Grace Kim",
    from: "KMIA",
    to: "KTEB",
    aircraft: "Global 6000",
    tailNumber: "N603GJ",
    operator: "VistaJet",
    broker: "Internal (Direct)",
    tripType: "Round Trip",
    status: "Confirmed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
  {
    id: "TJ-1064",
    tripId: "TRP-88256-A",
    date: "2026-12-09",
    time: "08:45",
    arrivalTime: "11:10",
    duration: "2h 25m",
    client: "Owen Bennett",
    from: "KTEB",
    to: "KPBI",
    aircraft: "Phenom 300",
    tailNumber: "N303PH",
    operator: "Flexjet",
    broker: "Skyline Partners",
    tripType: "One Way",
    status: "Confirmed",
    paymentStatus: "Cleared",
    fetApplied: "Yes (7.5%)",
  },
];
