export const transactionsStats = [
  { label: "TOTAL TRANSACTIONS", value: "7", tone: "foreground" },
  { label: "RECIVABLES", value: "2", tone: "success" },
  { label: "OPERATOR PAYMENTS", value: "5", tone: "warning" },
  { label: "COMMISSION", value: "0", tone: "foreground" },
];

export const transactionsStatusFilterOptions = [
  "All Status",
  "Paid",
  "Partially Paid",
  "Overdue",
  "Due",
  "Pending",
  "Cancelled",
];

export const transactionsData = [
  {
    id: "TRX-101",
    dated: "Aug 22, 2026",
    type: "Receivable",
    reference: "INV-2026-122",
    client: "Sophia Morgan",
    tripId: "TJ-1051",
    amount: "$2,100",
    amountRaw: 68000,
    fetRaw: 5100,
    paidRaw: 0,
    balanceRaw: 73100,
    balance: "$73,100",
    method: "Check",
    broker: "Barry",
    status: "Due",
    notes: "Charter payment receivable for Sophia Morgan flight.",
  },
  {
    id: "TRX-102",
    dated: "Aug 11, 2026",
    type: "Receivable",
    reference: "INV-2026-125",
    client: "Daniel Brooks",
    tripId: "TJ-1052",
    amount: "$1,800",
    amountRaw: 1800,
    fetRaw: 135,
    paidRaw: 1935,
    balanceRaw: 0,
    balance: "$0",
    method: "Zelle",
    broker: "Mark",
    status: "Paid",
    notes: "Full payment received via Zelle.",
  },
  {
    id: "TRX-103",
    dated: "Aug 20, 2026",
    type: "Operator Payment",
    reference: "INV-2026-123",
    client: "Sophia Morgan",
    tripId: "TJ-1043",
    amount: "$2,500",
    amountRaw: 2500,
    fetRaw: 0,
    paidRaw: 0,
    balanceRaw: 2500,
    balance: "$2,500",
    method: "Wire Transfer",
    broker: "Mark",
    status: "Pending",
    notes: "Pending operator confirmation.",
  },
  {
    id: "TRX-104",
    dated: "Aug 12, 2026",
    type: "Operator Payment",
    reference: "INV-2026-120",
    client: "Daniel Brooks",
    tripId: "TJ-1045",
    amount: "$1,800",
    amountRaw: 1800,
    fetRaw: 0,
    paidRaw: 1800,
    balanceRaw: 0,
    balance: "$0",
    method: "Check",
    broker: "Barry",
    status: "Paid",
    notes: "Check cleared by bank.",
  },
  {
    id: "TRX-105",
    dated: "Aug 10, 2026",
    type: "Operator Payment",
    reference: "INV-2026-121",
    client: "Sophia Morgan",
    tripId: "TJ-1026",
    amount: "$1,200",
    amountRaw: 1200,
    fetRaw: 0,
    paidRaw: 600,
    balanceRaw: 600,
    balance: "$600",
    method: "Wire Transfer",
    broker: "Mark",
    status: "Partially Paid",
    notes: "50% deposit paid.",
  },
  {
    id: "TRX-106",
    dated: "Aug 16, 2026",
    type: "Operator Payment",
    reference: "INV-2026-128",
    client: "Daniel Brooks",
    tripId: "TJ-1026",
    amount: "$1,500",
    amountRaw: 1500,
    fetRaw: 0,
    paidRaw: 0,
    balanceRaw: 1500,
    balance: "$1,500",
    method: "Zelle",
    broker: "Mark",
    status: "Pending",
    notes: "",
  },
  {
    id: "TRX-107",
    dated: "Aug 25, 2026",
    type: "Operator Payment",
    reference: "INV-2026-129",
    client: "FlexJet Operator",
    tripId: "TJ-1048",
    amount: "$3,200",
    amountRaw: 3200,
    fetRaw: 0,
    paidRaw: 0,
    balanceRaw: 3200,
    balance: "$3,200",
    method: "ACH",
    broker: "Barry",
    status: "Due",
    notes: "Operator flight fee.",
  },
];
