export const tripsStats = [
  { label: "Active Trips", value: "9", tone: "foreground" },
  { label: "In Flight", value: "1", tone: "warning" },
  { label: "Confirmed / Booked", value: "4", tone: "info" },
  { label: "Payment Attention", value: "2", tone: "destructive" },
  { label: "Total Revenue", value: "$475k", tone: "foreground" },
  { label: "Total Profit", value: "$84k", tone: "success" },
];

export const tripStatusOptions = ["All", "Confirmed", "Booked", "Sourcing", "Requested", "In Flight", "Completed"];
export const tripBrokerOptions = ["All", "Benny", "Mark", "Barry", "Ari"];
export const tripPaymentOptions = ["All", "Paid", "Pending", "Partially Paid", "Quoted"];

export const trips = [
  {
    id: "#TJ-1048",
    client: "Jonathan Reed",
    broker: "Benny",
    from: "KTEB",
    to: "KPBI",
    departure: "Aug 15, 2026",
    return: "Aug 18, 2026",
    aircraft: "Challenger 350",
    operator: "Jet Aviation",
    status: "Confirmed",
    clientPmt: "Paid",
    opPmt: "Paid",
    fet: "$1,500",
    profit: "$8,500",
    nextAction: "Send itinerary",
  },
  {
    id: "TJ-2402",
    client: "Hope Sterling",
    broker: "Benny",
    from: "KTEB",
    to: "KMIA",
    departure: "Aug 20, 2026",
    return: "Aug 23, 2026",
    aircraft: "Gulfstream G450",
    operator: "Air Charter Group",
    status: "Booked",
    clientPmt: "Partially Paid",
    opPmt: "Paid",
    fet: "$2,250",
    profit: "$17,000",
    nextAction: "Collect balance",
  },
  {
    id: "TJ-2403",
    client: "Emily Carter",
    broker: "Mark",
    from: "KMIA",
    to: "EGLL",
    departure: "Sep 3, 2026",
    return: "Sep 10, 2026",
    aircraft: "Global 7500",
    operator: "VistaJet",
    status: "Booked",
    clientPmt: "Quoted",
    opPmt: "Pending",
    fet: "$2,775",
    profit: "$37,000",
    nextAction: "Await client",
  },
  {
    id: "TJ-2404",
    client: "Daniel Brooks",
    broker: "Benny",
    from: "KVNY",
    to: "KASE",
    departure: "Aug 20, 2026",
    return: "---",
    aircraft: "Citation CJ3+",
    operator: "Rocky Mountain",
    status: "Confirmed",
    clientPmt: "Paid",
    opPmt: "Pending",
    fet: "$397",
    profit: "$5,300",
    nextAction: "Send final docs",
  },
  {
    id: "TJ-2405",
    client: "Sophia Morgan",
    broker: "Ari",
    from: "KTEB",
    to: "LFPB",
    departure: "Sep 20, 2026",
    return: "Sep 27, 2026",
    aircraft: "Global 6000",
    operator: "Gama Aviation",
    status: "Sourcing",
    clientPmt: "Pending",
    opPmt: "Pending",
    fet: "---",
    profit: "---",
    nextAction: "Source operator",
  },
  {
    id: "TJ-2406",
    client: "Marcus Webb",
    broker: "Barry",
    from: "KH...",
    to: "MM...",
    departure: "Aug 28, 2026",
    return: "Sep 2, 2026",
    aircraft: "Heavy Jet TBD",
    operator: "TBD",
    status: "Requested",
    clientPmt: "Pending",
    opPmt: "Pending",
    fet: "---",
    profit: "---",
    nextAction: "Source operator",
  },
  {
    id: "TJ-2407",
    client: "Alexis Reyes",
    broker: "Ari",
    from: "KLAS",
    to: "KTEB",
    departure: "Aug 25, 2026",
    return: "---",
    aircraft: "Gulfstream G550",
    operator: "Las Vegas Air Charter",
    status: "Booked",
    clientPmt: "Partially Paid",
    opPmt: "Pending",
    fet: "$787",
    profit: "$10,500",
    nextAction: "Collect final payment",
  },
  {
    id: "TJ-2408",
    client: "Tyler Grant",
    broker: "Barry",
    from: "KM...",
    to: "KFLL",
    departure: "Sep 12, 2026",
    return: "Sep 15, 2026",
    aircraft: "Hawker 900XP",
    operator: "Midway Charter",
    status: "Sourcing",
    clientPmt: "Pending",
    opPmt: "Pending",
    fet: "---",
    profit: "---",
    nextAction: "Request quotes",
  },
  {
    id: "TJ-2399",
    client: "Robert Walsh",
    broker: "Barry",
    from: "KTEB",
    to: "KPBI",
    departure: "Aug 16, 2026",
    return: "---",
    aircraft: "Citation Latitude",
    operator: "Global Wings",
    status: "In Flight",
    clientPmt: "Paid",
    opPmt: "Paid",
    fet: "$1,125",
    profit: "$3,500",
    nextAction: "Track flight",
  },
  {
    id: "TJ-2390",
    client: "David Chen",
    broker: "Mark",
    from: "KLAX",
    to: "KSFO",
    departure: "Aug 5, 2026",
    return: "---",
    aircraft: "Phenom 300",
    operator: "Pacific Charter",
    status: "Completed",
    clientPmt: "Paid",
    opPmt: "Paid",
    fet: "$600",
    profit: "$2,400",
    nextAction: "---",
  },
  {
    id: "TJ-2411",
    client: "Natalie Brooks",
    broker: "Mark",
    from: "KJFK",
    to: "KMIA",
    departure: "Sep 8, 2026",
    return: "Sep 12, 2026",
    aircraft: "Citation XLS",
    operator: "NetJets",
    status: "Confirmed",
    clientPmt: "Paid",
    opPmt: "Paid",
    fet: "$1,980",
    profit: "$6,200",
    nextAction: "Confirm catering",
  },
  {
    id: "TJ-2412",
    client: "Chris Dalton",
    broker: "Ari",
    from: "KDAL",
    to: "KASE",
    departure: "Sep 18, 2026",
    return: "Sep 21, 2026",
    aircraft: "King Air 350",
    operator: "Wheels Up",
    status: "Requested",
    clientPmt: "Pending",
    opPmt: "Pending",
    fet: "---",
    profit: "---",
    nextAction: "Source operator",
  },
];
