export const usersRolesStats = [
  { label: "TOTAL USERS", value: "6", tone: "foreground" },
  { label: "ACTIVE", value: "5", tone: "success" },
  { label: "ADMINS", value: "1", tone: "warning" },
  { label: "BROKERS", value: "4", tone: "foreground" },
];

export const userRoleOptions = ["All Roles", "Admin", "Senior Broker", "Broker", "Assistant"];
export const userStatusOptions = ["All Status", "Active", "Inactive", "Deactivated", "Pending"];

export const usersData = [
  {
    id: "USR-001",
    name: "Ari Wohl",
    email: "ari@tribecajets.com",
    role: "Admin",
    permissionLevel: "Admin",
    activeLeads: 4,
    activeTrips: 3,
    conversionRate: "42%",
    revenue: "$326,000",
    revenueRaw: 326000,
    lastLogin: "Aug 20, 2026",
    status: "Active",
  },
  {
    id: "USR-002",
    name: "Barry Wilson",
    email: "barry@tribecajets.com",
    role: "Broker",
    permissionLevel: "High",
    activeLeads: 4,
    activeTrips: 7,
    conversionRate: "68%",
    revenue: "$485,000",
    revenueRaw: 485000,
    lastLogin: "Aug 20, 2026",
    status: "Active",
  },
  {
    id: "USR-003",
    name: "Mark Evans",
    email: "mark@tribecajets.com",
    role: "Broker",
    permissionLevel: "Medium",
    activeLeads: 3,
    activeTrips: 6,
    conversionRate: "54%",
    revenue: "$326,000",
    revenueRaw: 326000,
    lastLogin: "Aug 20, 2026",
    status: "Active",
  },
  {
    id: "USR-004",
    name: "Benny Carter",
    email: "enny@tribecajets.com",
    role: "Broker",
    permissionLevel: "Medium",
    activeLeads: 3,
    activeTrips: 4,
    conversionRate: "61%",
    revenue: "$326,000",
    revenueRaw: 326000,
    lastLogin: "Aug 20, 2026",
    status: "Active",
  },
  {
    id: "USR-005",
    name: "Lisa Chen",
    email: "lisa@tribecajets.com",
    role: "Assistant",
    permissionLevel: "Low",
    activeLeads: 0,
    activeTrips: 0,
    conversionRate: "0%",
    revenue: "$326,000",
    revenueRaw: 326000,
    lastLogin: "Aug 20, 2026",
    status: "Active",
  },
  {
    id: "USR-006",
    name: "Tom Walsh",
    email: "tom@tribecajets.com",
    role: "Broker",
    permissionLevel: "Medium",
    activeLeads: 1,
    activeTrips: 0,
    conversionRate: "35%",
    revenue: "$326,000",
    revenueRaw: 326000,
    lastLogin: "Aug 20, 2026",
    status: "Inactive",
  },
];

export const permissionMatrixRows = [
  {
    permission: "View Dashboard",
    admin: true,
    seniorBroker: true,
    broker: true,
    assistant: true,
  },
  {
    permission: "View All Trips",
    admin: true,
    seniorBroker: true,
    broker: "Own Only",
    assistant: "Assigned",
  },
  {
    permission: "Create/Edit Trips",
    admin: true,
    seniorBroker: true,
    broker: true,
    assistant: false,
  },
  {
    permission: "Delete Trips",
    admin: true,
    seniorBroker: false,
    broker: false,
    assistant: false,
  },
  {
    permission: "View Financials",
    admin: true,
    seniorBroker: true,
    broker: "Own",
    assistant: false,
  },
  {
    permission: "Export Data",
    admin: true,
    seniorBroker: true,
    broker: false,
    assistant: false,
  },
  {
    permission: "Manage Users",
    admin: true,
    seniorBroker: false,
    broker: false,
    assistant: false,
  },
  {
    permission: "Operator Sourcing",
    admin: true,
    seniorBroker: true,
    broker: true,
    assistant: "View",
  },
];
